using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CpuGenerator
{
    // TODO Cleanup and finish generator
    class Generator
    {
        public Generator()
        {
        }

        public void Generate(TextWriter writer)
        {
            writer.WriteLine("//-------------------------------------------------------------------------------------");
            writer.WriteLine("// This is file was generated by CpuGenerator.");
            writer.WriteLine("// Do not edit this file manually or all your changes will be lost after re-generation.");
            writer.WriteLine("//-------------------------------------------------------------------------------------");
            writer.WriteLine();

            writer.WriteLine("#include \"Processor.h\"");
            writer.WriteLine();

            List<string> opcodes = Properties.Resources.Opcodes.Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries).ToList();
            List<string> opcodesCB = Properties.Resources.OpcodesCB.Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries).ToList();

            if (opcodes.Count != 256 && opcodesCB.Count != 256)
                return;

            writer.WriteLine("void Processor::InitOpcodes()");
            writer.WriteLine("{");

            for (int i = 0; i < 256; i++)
            {
                string line = opcodes.ElementAt(i);

                if ((line != "UNDEFINED") && (line != "CB_OPCODE"))
                    MapOpcodes(writer, i, line);
                else
                    MapInvalid(writer, i, line);
            }

            writer.WriteLine();
            writer.WriteLine("\t// CB Obcodes");

            for (int i = 0; i < 256; i++)
            {
                string line = opcodesCB.ElementAt(i);

                MapCBOpcodes(writer, i, line);
            }

            writer.WriteLine("}");
            writer.WriteLine();

            for (int i = 0; i < 256; i++)
            {
                string line = opcodes.ElementAt(i);

                if ((line != "UNDEFINED") && (line != "CB_OPCODE"))
                    GenerateMethod(writer, i, line);
            }

            writer.WriteLine("// CB Obcodes");
            writer.WriteLine();

            for (int i = 0; i < 256; i++)
            {
                string line = opcodesCB.ElementAt(i);

                GenerateMethod(writer, i, line);
            }
        }

        public void GenerateMethod(TextWriter writer, int op, string line)
        {
            Opcode opcode;
            ParseOpcode(line, out opcode);

            writer.WriteLine("/* {0} */", line.Replace(",", ", "));
            writer.WriteLine("void Processor::{0}() // 0x{1:X2}", opcode.ToFunctionName(), op);
            writer.WriteLine("{");

            WriteOpcodeStub(writer, opcode);

            writer.WriteLine("}");
            writer.WriteLine();
        }

        public void ParseOpcode(string opString, out Opcode opcode)
        {
            var instr = opString.Split(' ', ',');
            var instrLength = instr.Length;

            opcode = new Opcode();
            opcode.Operation = instr[0];
            opcode.NumberOfOperands = instrLength - 1;

            if (opcode.NumberOfOperands == 1)
            {
                opcode.FirstOperand = instr[1];
                opcode.SecondOperand = string.Empty;
            }
            else if (opcode.NumberOfOperands == 2)
            {
                opcode.FirstOperand = instr[1];
                opcode.SecondOperand = instr[2];
            }
        }

        private void WriteOpcodeStub(TextWriter writer, Opcode opcode)
        {
            string operation = opcode.Operation;
            string firstOperand = opcode.FirstOperand;
            string secondOperand = opcode.SecondOperand;

            string first = GetStoreStub(firstOperand);
            string second = GetLoadStub(secondOperand);

            switch (operation)
            {
                case "NOP":
                    break;
                case "STOP":
                    writer.WriteLine("\tPC++;");
                    break;
                case "LD":
                    if (firstOperand != secondOperand)
                    {
                        if (firstOperand == "HL" && secondOperand == "SP+n")
                        {
                            WriteHLSPN(writer, opcode);
                        }
                        else
                        {
                            if (firstOperand == "(nn)" && secondOperand == "A")
                                writer.WriteLine("\tmemory->WriteByte(memory->ReadWord(PC), A);");
                            else
                                writer.WriteLine("\t" + string.Format(first, second));

                            if (secondOperand == "nn" || secondOperand == "(nn)" || firstOperand == "(nn)")
                                writer.WriteLine("\tPC += 2;");
                        }
                    }
                    break;
                case "INC":
                    if (firstOperand == "BC" || firstOperand == "DE" || firstOperand == "HL" || firstOperand == "SP")
                        WriteIncWord(writer, opcode);
                    else
                        WriteIncByte(writer, opcode);
                    break;
                case "DEC":
                    if (firstOperand == "BC" || firstOperand == "DE" || firstOperand == "HL" || firstOperand == "SP")
                        WriteDecWord(writer, opcode);
                    else
                        WriteDecByte(writer, opcode);
                    break;
                case "AND":
                    WriteAnd(writer, opcode);
                    break;
                case "OR":
                    WriteOr(writer, opcode);
                    break;
                case "XOR":
                    WriteXor(writer, opcode);
                    break;
                case "ADD":
                    if (firstOperand == "HL" || firstOperand == "SP")
                        WriteAddWord(writer, opcode);
                    else
                        WriteAdd(writer, opcode);
                    break;
                case "ADC":
                    WriteAdc(writer, opcode);
                    break;
                case "SUB":
                    WriteSub(writer, opcode);
                    break;
                case "SBC":
                    WriteSbc(writer, opcode);
                    break;
                case "DI":
                    WriteDi(writer, opcode);
                    break;
                case "EI":
                    WriteEi(writer, opcode);
                    break;
                case "BIT":
                    WriteBit(writer, opcode);
                    break;
                case "SET":
                    if (secondOperand != "(HL)")
                        WriteSet(writer, opcode);
                    else
                        WriteHLSet(writer, opcode);
                    break;
                case "RES":
                    if (secondOperand != "(HL)")
                        WriteRes(writer, opcode);
                    else
                        WriteHLRes(writer, opcode);
                        break;
                case "CALL":
                        WriteCall(writer, opcode);
                        break;
                case "RET":
                        WriteRet(writer, opcode);
                        break;
                case "RETI":
                        WriteReti(writer, opcode);
                        break;
                case "PUSH":
                        WritePush(writer, opcode);
                        break;
                case "POP":
                        WritePop(writer, opcode);
                        break;
                case "JR":
                        WriteJr(writer, opcode);
                        break;
                case "JP":
                        if (firstOperand == "(HL)")
                            writer.WriteLine("\tPC = HL;");
                        else
                            WriteJp(writer, opcode);
                        break;
                case "DAA":
                        WriteDaa(writer, opcode);
                        break;
                case "CPL":
                        WriteCpl(writer, opcode);
                        break;
                case "CCF":
                        WriteCcf(writer, opcode);
                        break;
                case "SCF":
                        WriteScf(writer, opcode);
                        break;
                case "CP":
                        WriteCp(writer, opcode);
                        break;
                case "HALT":
                        WriteHalt(writer, opcode);
                        break;
                case "RST":
                        WriteRst(writer, opcode);
                        break;
                case "SWAP":
                        if (firstOperand != "(HL)")
                            WriteSwap(writer, opcode);
                        else
                            WriteSwapHL(writer, opcode);
                        break;
                case "RL":
                        WriteRl(writer, opcode);
                        break;
                case "RLC":
                        WriteRlc(writer, opcode);
                        break;
                case "RR":
                        WriteRr(writer, opcode);
                        break;
                case "RRC":
                        WriteRrc(writer, opcode);
                        break;
                case "RLA":
                        WriteRl(writer, opcode, true);
                        break;
                case "RLCA":
                        WriteRlc(writer, opcode, true);
                        break;
                case "RRA":
                        WriteRr(writer, opcode, true);
                        break;
                case "RRCA":
                        WriteRrc(writer, opcode, true);
                        break;
                case "SLA":
                        WriteSla(writer, opcode, true);
                        break;
                case "SRA":
                        WriteSra(writer, opcode, true);
                        break;
                case "SRL":
                        WriteSrl(writer, opcode, true);
                        break;
                default:
                    writer.WriteLine("\t// Not implemented yet");
                    writer.WriteLine("\tUnknownOpcode();");
                    break;
            }
        }

        private string GetCondition(string operand)
        {
            switch (operand)
            {
                case "NZ":
                    return "!IsFlagSet(FLAG_ZERO)";
                case "Z":
                    return "IsFlagSet(FLAG_ZERO)";
                case "NC":
                    return "!IsFlagSet(FLAG_CARRY)";
                case "C":
                    return "IsFlagSet(FLAG_CARRY)";
                default:
                    return "";
            }
        }

        private string GetStoreStub(string operand)
        {
            switch (operand)
            {
                case "(0xFF00+n)":
                    return "memory->WriteByte(0xFF00 + memory->ReadByte(PC++), {0});";
                case "(0xFF00+C)":
                    return "memory->WriteByte(0xFF00 + C, {0});";
                case "(nn)":
                    return "memory->WriteWord(memory->ReadWord(PC), {0});";
                case "(BC)":
                case "(DE)":
                case "(HL)":
                {
                    string op = operand.Replace("(", "").Replace(")", "");
                    return "memory->WriteByte(" + op + ", {0});";
                }
                case "(HLD)":
                {
                    string op = operand.Replace("(", "").Replace(")", "").Replace("D", "");
                    return "memory->WriteByte(" + op + "--, {0});";
                }
                case "(HLI)":
                {
                    string op = operand.Replace("(", "").Replace(")", "").Replace("I", "");
                    return "memory->WriteByte(" + op + "++, {0});";
                }
                default:
                    return operand + " = {0};";
            }
        }

        private string GetLoadStub(string operand)
        {
            switch (operand)
            {
                case "(0xFF00+n)":
                    return "memory->ReadByte(0xFF00 + memory->ReadByte(PC++))";
                case "(0xFF00+C)":
                    return "memory->ReadByte(0xFF00 + C)";
                case "n":
                    return "memory->ReadByte(PC++)";
                case "nn":
                    return "memory->ReadWord(PC)";
                case "(nn)":
                    return "memory->ReadByte(memory->ReadWord(PC))";
                case "(BC)":
                case "(DE)":
                case "(HL)":
                {
                    string op = operand.Replace("(", "").Replace(")", "");
                    return "memory->ReadByte(" + op + ")";
                }
                case "(HLD)":
                {
                    string op = operand.Replace("(", "").Replace(")", "").Replace("D", "");
                    return "memory->ReadByte(" + op + "--)";
                }
                case "(HLI)":
                {
                    string op = operand.Replace("(", "").Replace(")", "").Replace("I", "");
                    return "memory->ReadByte(" + op + "++)";
                }
                default:
                    return operand;
            }
        }

        public void MapOpcodes(TextWriter writer, int op, string line)
        {
            Opcode opcode;
            ParseOpcode(line, out opcode);

            var funcName = opcode.ToFunctionName();

            writer.WriteLine("\topcodes[0x{0:X2}] = std::bind(&Processor::{1}, this);", op, funcName);
        }

        public void MapInvalid(TextWriter writer, int op, string line)
        {
            writer.WriteLine("\topcodes[0x{0:X2}] = std::bind(&Processor::InvalidOpcode, this);", op);
        }

        public void MapCBOpcodes(TextWriter writer, int op, string line)
        {
            Opcode opcode;
            ParseOpcode(line, out opcode);

            var funcName = opcode.ToFunctionName();

            writer.WriteLine("\topcodesCB[0x{0:X2}] = std::bind(&Processor::{1}, this);", op, funcName);
        }

        #region Opcode Templates

        public void WriteIncByte(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\t" + GetStoreStub(opcode.FirstOperand), string.Format("Inc({0})", GetLoadStub(opcode.FirstOperand)));
        }

        public void WriteIncWord(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\t{0}++;", opcode.FirstOperand);
        }

        public void WriteDecByte(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\t" + GetStoreStub(opcode.FirstOperand), string.Format("Dec({0})", GetLoadStub(opcode.FirstOperand)));
        }

        public void WriteDecWord(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\t{0}--;", opcode.FirstOperand);
        }

        public void WriteAnd(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tA &= {0};", GetLoadStub(opcode.FirstOperand));
            writer.WriteLine("\tSetFlag(FLAG_HALFCARRY);");
            writer.WriteLine("\tif (A == 0) EnableFlag(FLAG_ZERO);");
        }

        public void WriteOr(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tA |= {0};", GetLoadStub(opcode.FirstOperand));
            writer.WriteLine("\tClearFlags();");
            writer.WriteLine("\tif (A == 0) EnableFlag(FLAG_ZERO);");
        }

        public void WriteXor(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tA ^= {0};", GetLoadStub(opcode.FirstOperand));
            writer.WriteLine("\tClearFlags();");
            writer.WriteLine("\tif (A == 0) EnableFlag(FLAG_ZERO);");
        }

        public void WriteAddWord(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tAdd{0}({1});", opcode.FirstOperand, GetLoadStub(opcode.SecondOperand));
        }

        public void WriteAdd(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tAdd({0});", GetLoadStub(opcode.SecondOperand));
        }

        public void WriteAdc(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tAdc({0});", GetLoadStub(opcode.SecondOperand));
        }

        public void WriteSub(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tSub({0});", GetLoadStub(opcode.FirstOperand));
        }

        public void WriteSbc(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tSbc({0});", GetLoadStub(opcode.SecondOperand));
        }

        public void WriteDaa(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tuint8 reg = A;\n");
            writer.WriteLine("\tif (IsFlagSet(FLAG_SUB))\n\t{");
            writer.WriteLine("\t\tif ((reg & 0x0F) > 9 || IsFlagSet(FLAG_HALFCARRY))");
            writer.WriteLine("\t\t{");
            writer.WriteLine("\t\t\treg -= 0x06;");
            writer.WriteLine("\t\t}");
            writer.WriteLine("\t\telse if ((reg & 0x9F) > 9 || IsFlagSet(FLAG_CARRY))");
            writer.WriteLine("\t\t{");
            writer.WriteLine("\t\t\treg -= 0x60;");
            writer.WriteLine("\t\t}");
            writer.WriteLine("\t}");
            writer.WriteLine("\telse\n\t{");
            writer.WriteLine("\t\tif ((reg & 0x0F) > 9 || IsFlagSet(FLAG_HALFCARRY))");
            writer.WriteLine("\t\t{");
            writer.WriteLine("\t\t\treg += 0x06;");
            writer.WriteLine("\t\t}");
            writer.WriteLine("\t\telse if ((reg & 0x9F) > 9 || IsFlagSet(FLAG_CARRY))");
            writer.WriteLine("\t\t{");
            writer.WriteLine("\t\t\treg += 0x60;");
            writer.WriteLine("\t\t}\n");
            writer.WriteLine("\t}");
            writer.WriteLine("\tDisableFlag(FLAG_HALFCARRY);");
            writer.WriteLine("\tif (reg == 0) EnableFlag(FLAG_ZERO);\n");
            writer.WriteLine("\tA = reg;");
        }

        public void WriteDi(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\time = false;");
        }

        public void WriteEi(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\time = true;");
        }

        public void WriteBit(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tif ((({0} >> {1}) & 0x01) == 0) EnableFlag(FLAG_ZERO);", GetLoadStub(opcode.SecondOperand), opcode.FirstOperand);
            writer.WriteLine("\telse DisableFlag(FLAG_ZERO);");
            writer.WriteLine("\tDisableFlag(FLAG_SUB);");
            writer.WriteLine("\tEnableFlag(FLAG_HALFCARRY);");
        }

        public void WriteSet(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tSetBit({0}, {1});", opcode.SecondOperand, opcode.FirstOperand);
        }

        public void WriteRes(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tResetBit({0}, {1});", opcode.SecondOperand, opcode.FirstOperand);
        }

        public void WriteHLSet(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tuint8 result = memory->ReadByte(HL);");
            writer.WriteLine("\tSetBit(result, {0});", opcode.FirstOperand);
            writer.WriteLine("\tmemory->WriteByte(HL, result);");
        }

        public void WriteHLRes(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tuint8 result = memory->ReadByte(HL);");
            writer.WriteLine("\tResetBit(result, {0});", opcode.FirstOperand);
            writer.WriteLine("\tmemory->WriteByte(HL, result);");
        }

        public void WriteCall(TextWriter writer, Opcode opcode)
        {
            string cond = GetCondition(opcode.FirstOperand);
            string tabs = "\t";
            if (!string.IsNullOrEmpty(cond))
            {
                tabs += "\t";
                writer.WriteLine("\tif (" + cond + ")\n\t{");
                writer.WriteLine(tabs + "condition = true;");
            }
            writer.WriteLine(tabs + "uint16 address = memory->ReadWord(PC);");
            writer.WriteLine(tabs + "PC += 2;");
            writer.WriteLine(tabs + "StackPush(PC);");
            writer.WriteLine(tabs + "PC = address;");
            if (cond != string.Empty)
            {
                writer.WriteLine("\t}\n\telse\n\t{\n\t\tPC += 2;\n\t}");
            }
        }

        public void WriteRet(TextWriter writer, Opcode opcode)
        {
            string cond = GetCondition(opcode.FirstOperand);
            string tabs = "\t";
            if (!string.IsNullOrEmpty(cond))
            {
                tabs += "\t";
                writer.WriteLine("\tif (" + cond + ")\n\t{");
                writer.WriteLine(tabs + "condition = true;");
            }
            writer.WriteLine(tabs + "StackPop(PC);");
            if (cond != string.Empty)
            {
                writer.WriteLine("\t}");
            }
        }

        public void WriteReti(TextWriter writer, Opcode opcode)
        {
            WriteRet(writer, opcode);
            writer.WriteLine("\time = true;");
        }

        public void WritePush(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tStackPush({0});", opcode.FirstOperand);
        }

        public void WritePop(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tStackPop({0});", opcode.FirstOperand);
        }

        public void WriteJr(TextWriter writer, Opcode opcode)
        {
            string cond = GetCondition(opcode.FirstOperand);
            string tabs = "\t";
            if (!string.IsNullOrEmpty(cond))
            {
                tabs += "\t";
                writer.WriteLine("\tif (" + cond + ")\n\t{");
                writer.WriteLine(tabs + "condition = true;");
            }

            writer.WriteLine(tabs + "PC += static_cast<int8>(memory->ReadByte(PC++));");
            if (cond != string.Empty)
            {
                writer.WriteLine("\t}\n\telse\n\t{\n\t\tPC++;\n\t}");
            }
        }

        public void WriteJp(TextWriter writer, Opcode opcode)
        {
            string cond = GetCondition(opcode.FirstOperand);
            string tabs = "\t";
            if (!string.IsNullOrEmpty(cond))
            {
                tabs += "\t";
                writer.WriteLine("\tif (" + cond + ")\n\t{");
                writer.WriteLine(tabs + "condition = true;");
            }

            writer.WriteLine(tabs + "PC = memory->ReadWord(PC);");
            if (cond != string.Empty)
            {
                writer.WriteLine("\t}\n\telse\n\t{\n\t\tPC += 2;\n\t}");
            }
        }

        public void WriteCpl(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tA = ~A;");
            writer.WriteLine("\tEnableFlag(FLAG_HALFCARRY);");
            writer.WriteLine("\tEnableFlag(FLAG_SUB);");
        }

        public void WriteCcf(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tInvertFlag(FLAG_CARRY);");
            writer.WriteLine("\tDisableFlag(FLAG_HALFCARRY);");
            writer.WriteLine("\tDisableFlag(FLAG_SUB);");
        }

        public void WriteScf(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tEnableFlag(FLAG_CARRY);");
            writer.WriteLine("\tDisableFlag(FLAG_HALFCARRY);");
            writer.WriteLine("\tDisableFlag(FLAG_SUB);");
        }

        public void WriteCp(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tSetFlag(FLAG_SUB);");
            writer.WriteLine("\tif (A < {0}) EnableFlag(FLAG_CARRY);", GetLoadStub(opcode.FirstOperand));
            writer.WriteLine("\tif (A == {0}) EnableFlag(FLAG_ZERO);", GetLoadStub(opcode.FirstOperand));
            writer.WriteLine("\tif (((A - {0}) & 0xF) > (A & 0xF)) EnableFlag(FLAG_HALFCARRY);", GetLoadStub(opcode.FirstOperand));
        }

        public void WriteHalt(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\thalted = true;");
        }

        public void WriteRst(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tStackPush(PC);");
            writer.WriteLine("\tPC = {0};", string.IsNullOrEmpty(opcode.FirstOperand) ? "0x0000" : opcode.FirstOperand);
        }

        public void WriteSwap(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\t{0} = (({0} >> 4) & 0x0F) | (({0} << 4) & 0xF0);", opcode.FirstOperand);
            writer.WriteLine("\tClearFlags();");
            writer.WriteLine("\tif ({0} == 0) EnableFlag(FLAG_ZERO);", opcode.FirstOperand);
        }

        public void WriteSwapHL(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tuint8 val = memory->ReadByte(HL);");
            writer.WriteLine("\tmemory->WriteByte(HL, ((val >> 4) & 0x0F) | ((val << 4) & 0xF0));");
            writer.WriteLine("\tClearFlags();");
            writer.WriteLine("\tif (memory->ReadByte(HL) == 0) EnableFlag(FLAG_ZERO);");
        }

        public void WriteHLSPN(TextWriter writer, Opcode opcode)
        {
            writer.WriteLine("\tint8 n = static_cast<int8>(memory->ReadByte(PC++));");
            writer.WriteLine("\tHL = SP + n;");
            writer.WriteLine("\tClearFlags();");
            writer.WriteLine("\tif (((SP ^ n ^ HL) & 0x100) == 0x100)");
            writer.WriteLine("\t\tEnableFlag(FLAG_CARRY);");
            writer.WriteLine("\tif (((SP ^ n ^ HL) & 0x10) == 0x10)");
            writer.WriteLine("\t\tEnableFlag(FLAG_HALFCARRY);");
        }

        public void WriteRl(TextWriter writer, Opcode opcode, bool a = false)
        {
            string operand = a ? "A" : opcode.FirstOperand;
            writer.WriteLine("\t" + GetStoreStub(operand), string.Format("Rl({0})", GetLoadStub(operand)));
        }

        public void WriteRlc(TextWriter writer, Opcode opcode, bool a = false)
        {
            string operand = a ? "A" : opcode.FirstOperand;
            writer.WriteLine("\t" + GetStoreStub(operand), string.Format("Rlc({0})", GetLoadStub(operand)));
        }

        public void WriteRr(TextWriter writer, Opcode opcode, bool a = false)
        {
            string operand = a ? "A" : opcode.FirstOperand;
            writer.WriteLine("\t" + GetStoreStub(operand), string.Format("Rr({0})", GetLoadStub(operand)));
        }

        public void WriteRrc(TextWriter writer, Opcode opcode, bool a = false)
        {
            string operand = a ? "A" : opcode.FirstOperand;
            writer.WriteLine("\t" + GetStoreStub(operand), string.Format("Rrc({0})", GetLoadStub(operand)));
        }

        public void WriteSla(TextWriter writer, Opcode opcode, bool a = false)
        {
            writer.WriteLine("\t" + GetStoreStub(opcode.FirstOperand), string.Format("Sla({0})", GetLoadStub(opcode.FirstOperand)));
        }

        public void WriteSra(TextWriter writer, Opcode opcode, bool a = false)
        {
            writer.WriteLine("\t" + GetStoreStub(opcode.FirstOperand), string.Format("Sra({0})", GetLoadStub(opcode.FirstOperand)));
        }

        public void WriteSrl(TextWriter writer, Opcode opcode, bool a = false)
        {
            writer.WriteLine("\t" + GetStoreStub(opcode.FirstOperand), string.Format("Srl({0})", GetLoadStub(opcode.FirstOperand)));
        }

        #endregion
    }
}
