//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CpuGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CpuGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOP
        ///LD BC,nn
        ///LD (BC),A
        ///INC BC
        ///INC B
        ///DEC B
        ///LD B,n
        ///RLCA
        ///LD (nn),SP
        ///ADD HL,BC
        ///LD A,(BC)
        ///DEC BC
        ///INC C
        ///DEC C
        ///LD C,n
        ///RRCA
        ///STOP
        ///LD DE,nn
        ///LD (DE),A
        ///INC DE
        ///INC D
        ///DEC D
        ///LD D,n
        ///RLA
        ///JR n
        ///ADD HL,DE
        ///LD A,(DE)
        ///DEC DE
        ///INC E
        ///DEC E
        ///LD E,n
        ///RRA
        ///JR NZ,n
        ///LD HL,nn
        ///LD (HLI),A
        ///INC HL
        ///INC H
        ///DEC H
        ///LD H,n
        ///DAA
        ///JR Z,n
        ///ADD HL,HL
        ///LD A,(HLI)
        ///DEC HL
        ///INC L
        ///DEC L
        ///LD L,n
        ///CPL
        ///JR NC,n
        ///LD SP,nn
        ///LD (HLD),A
        ///INC SP
        ///INC (HL)
        ///DEC (HL)
        ///LD (HL),n
        ///SCF
        ///JR C,n
        ///ADD HL,SP
        ///LD A,(HLD)
        ///DEC SP
        ///INC A
        ///DE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Opcodes {
            get {
                return ResourceManager.GetString("Opcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RLC B
        ///RLC C
        ///RLC D
        ///RLC E
        ///RLC H
        ///RLC L
        ///RLC (HL)
        ///RLC A
        ///RRC B
        ///RRC C
        ///RRC D
        ///RRC E
        ///RRC H
        ///RRC L
        ///RRC (HL)
        ///RRC A
        ///RL B
        ///RL C
        ///RL D
        ///RL E
        ///RL H
        ///RL L 
        ///RL (HL)
        ///RL A
        ///RR B
        ///RR C
        ///RR D
        ///RR E
        ///RR H
        ///RR L
        ///RR (HL)
        ///RR A
        ///SLA B
        ///SLA C
        ///SLA D
        ///SLA E
        ///SLA H
        ///SLA L
        ///SLA (HL)
        ///SLA A
        ///SRA B
        ///SRA C
        ///SRA D
        ///SRA E
        ///SRA H
        ///SRA L
        ///SRA (HL)
        ///SRA A
        ///SWAP B
        ///SWAP C
        ///SWAP D
        ///SWAP E
        ///SWAP H
        ///SWAP L
        ///SWAP (HL)
        ///SWAP A
        ///SRL B
        ///SRL C
        ///SRL D
        ///SRL E
        ///SRL H
        ///SRL L
        ///SRL (HL)
        ///SRL A
        ///BIT 0 B
        ///BIT 0 C
        ///BIT 0 D
        ///BIT 0 E
        ///BIT 0 H
        ///BI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpcodesCB {
            get {
                return ResourceManager.GetString("OpcodesCB", resourceCulture);
            }
        }
    }
}
