//-------------------------------------------------------------------------------------
// This is file was generated by CpuGenerator.
// Do not edit this file manually or all your changes will be lost after re-generation.
//-------------------------------------------------------------------------------------

#include "Processor.h"
#include "BitUtil.h"

void Processor::InitOpcodes()
{
	opcodes[0x00] = std::bind(&Processor::NOP, this);
	opcodes[0x01] = std::bind(&Processor::LD_BC_nn, this);
	opcodes[0x02] = std::bind(&Processor::LD_MEM_BC_A, this);
	opcodes[0x03] = std::bind(&Processor::INC_BC, this);
	opcodes[0x04] = std::bind(&Processor::INC_B, this);
	opcodes[0x05] = std::bind(&Processor::DEC_B, this);
	opcodes[0x06] = std::bind(&Processor::LD_B_n, this);
	opcodes[0x07] = std::bind(&Processor::RLCA, this);
	opcodes[0x08] = std::bind(&Processor::LD_MEM_nn_SP, this);
	opcodes[0x09] = std::bind(&Processor::ADD_HL_BC, this);
	opcodes[0x0A] = std::bind(&Processor::LD_A_MEM_BC, this);
	opcodes[0x0B] = std::bind(&Processor::DEC_BC, this);
	opcodes[0x0C] = std::bind(&Processor::INC_C, this);
	opcodes[0x0D] = std::bind(&Processor::DEC_C, this);
	opcodes[0x0E] = std::bind(&Processor::LD_C_n, this);
	opcodes[0x0F] = std::bind(&Processor::RRCA, this);
	opcodes[0x10] = std::bind(&Processor::STOP, this);
	opcodes[0x11] = std::bind(&Processor::LD_DE_nn, this);
	opcodes[0x12] = std::bind(&Processor::LD_MEM_DE_A, this);
	opcodes[0x13] = std::bind(&Processor::INC_DE, this);
	opcodes[0x14] = std::bind(&Processor::INC_D, this);
	opcodes[0x15] = std::bind(&Processor::DEC_D, this);
	opcodes[0x16] = std::bind(&Processor::LD_D_n, this);
	opcodes[0x17] = std::bind(&Processor::RLA, this);
	opcodes[0x18] = std::bind(&Processor::JR_n, this);
	opcodes[0x19] = std::bind(&Processor::ADD_HL_DE, this);
	opcodes[0x1A] = std::bind(&Processor::LD_A_MEM_DE, this);
	opcodes[0x1B] = std::bind(&Processor::DEC_DE, this);
	opcodes[0x1C] = std::bind(&Processor::INC_E, this);
	opcodes[0x1D] = std::bind(&Processor::DEC_E, this);
	opcodes[0x1E] = std::bind(&Processor::LD_E_n, this);
	opcodes[0x1F] = std::bind(&Processor::RRA, this);
	opcodes[0x20] = std::bind(&Processor::JR_NZ_n, this);
	opcodes[0x21] = std::bind(&Processor::LD_HL_nn, this);
	opcodes[0x22] = std::bind(&Processor::LD_MEM_HLI_A, this);
	opcodes[0x23] = std::bind(&Processor::INC_HL, this);
	opcodes[0x24] = std::bind(&Processor::INC_H, this);
	opcodes[0x25] = std::bind(&Processor::DEC_H, this);
	opcodes[0x26] = std::bind(&Processor::LD_H_n, this);
	opcodes[0x27] = std::bind(&Processor::DAA, this);
	opcodes[0x28] = std::bind(&Processor::JR_Z_n, this);
	opcodes[0x29] = std::bind(&Processor::ADD_HL_HL, this);
	opcodes[0x2A] = std::bind(&Processor::LD_A_MEM_HLI, this);
	opcodes[0x2B] = std::bind(&Processor::DEC_HL, this);
	opcodes[0x2C] = std::bind(&Processor::INC_L, this);
	opcodes[0x2D] = std::bind(&Processor::DEC_L, this);
	opcodes[0x2E] = std::bind(&Processor::LD_L_n, this);
	opcodes[0x2F] = std::bind(&Processor::CPL, this);
	opcodes[0x30] = std::bind(&Processor::JR_NC_n, this);
	opcodes[0x31] = std::bind(&Processor::LD_SP_nn, this);
	opcodes[0x32] = std::bind(&Processor::LD_MEM_HLD_A, this);
	opcodes[0x33] = std::bind(&Processor::INC_SP, this);
	opcodes[0x34] = std::bind(&Processor::INC_MEM_HL, this);
	opcodes[0x35] = std::bind(&Processor::DEC_MEM_HL, this);
	opcodes[0x36] = std::bind(&Processor::LD_MEM_HL_n, this);
	opcodes[0x37] = std::bind(&Processor::SCF, this);
	opcodes[0x38] = std::bind(&Processor::JR_C_n, this);
	opcodes[0x39] = std::bind(&Processor::ADD_HL_SP, this);
	opcodes[0x3A] = std::bind(&Processor::LD_A_MEM_HLD, this);
	opcodes[0x3B] = std::bind(&Processor::DEC_SP, this);
	opcodes[0x3C] = std::bind(&Processor::INC_A, this);
	opcodes[0x3D] = std::bind(&Processor::DEC_A, this);
	opcodes[0x3E] = std::bind(&Processor::LD_A_n, this);
	opcodes[0x3F] = std::bind(&Processor::CCF, this);
	opcodes[0x40] = std::bind(&Processor::LD_B_B, this);
	opcodes[0x41] = std::bind(&Processor::LD_B_C, this);
	opcodes[0x42] = std::bind(&Processor::LD_B_D, this);
	opcodes[0x43] = std::bind(&Processor::LD_B_E, this);
	opcodes[0x44] = std::bind(&Processor::LD_B_H, this);
	opcodes[0x45] = std::bind(&Processor::LD_B_L, this);
	opcodes[0x46] = std::bind(&Processor::LD_B_MEM_HL, this);
	opcodes[0x47] = std::bind(&Processor::LD_B_A, this);
	opcodes[0x48] = std::bind(&Processor::LD_C_B, this);
	opcodes[0x49] = std::bind(&Processor::LD_C_C, this);
	opcodes[0x4A] = std::bind(&Processor::LD_C_D, this);
	opcodes[0x4B] = std::bind(&Processor::LD_C_E, this);
	opcodes[0x4C] = std::bind(&Processor::LD_C_H, this);
	opcodes[0x4D] = std::bind(&Processor::LD_C_L, this);
	opcodes[0x4E] = std::bind(&Processor::LD_C_MEM_HL, this);
	opcodes[0x4F] = std::bind(&Processor::LD_C_A, this);
	opcodes[0x50] = std::bind(&Processor::LD_D_B, this);
	opcodes[0x51] = std::bind(&Processor::LD_D_C, this);
	opcodes[0x52] = std::bind(&Processor::LD_D_D, this);
	opcodes[0x53] = std::bind(&Processor::LD_D_E, this);
	opcodes[0x54] = std::bind(&Processor::LD_D_H, this);
	opcodes[0x55] = std::bind(&Processor::LD_D_L, this);
	opcodes[0x56] = std::bind(&Processor::LD_D_MEM_HL, this);
	opcodes[0x57] = std::bind(&Processor::LD_D_A, this);
	opcodes[0x58] = std::bind(&Processor::LD_E_B, this);
	opcodes[0x59] = std::bind(&Processor::LD_E_C, this);
	opcodes[0x5A] = std::bind(&Processor::LD_E_D, this);
	opcodes[0x5B] = std::bind(&Processor::LD_E_E, this);
	opcodes[0x5C] = std::bind(&Processor::LD_E_H, this);
	opcodes[0x5D] = std::bind(&Processor::LD_E_L, this);
	opcodes[0x5E] = std::bind(&Processor::LD_E_MEM_HL, this);
	opcodes[0x5F] = std::bind(&Processor::LD_E_A, this);
	opcodes[0x60] = std::bind(&Processor::LD_H_B, this);
	opcodes[0x61] = std::bind(&Processor::LD_H_C, this);
	opcodes[0x62] = std::bind(&Processor::LD_H_D, this);
	opcodes[0x63] = std::bind(&Processor::LD_H_E, this);
	opcodes[0x64] = std::bind(&Processor::LD_H_H, this);
	opcodes[0x65] = std::bind(&Processor::LD_H_L, this);
	opcodes[0x66] = std::bind(&Processor::LD_H_MEM_HL, this);
	opcodes[0x67] = std::bind(&Processor::LD_H_A, this);
	opcodes[0x68] = std::bind(&Processor::LD_L_B, this);
	opcodes[0x69] = std::bind(&Processor::LD_L_C, this);
	opcodes[0x6A] = std::bind(&Processor::LD_L_D, this);
	opcodes[0x6B] = std::bind(&Processor::LD_L_E, this);
	opcodes[0x6C] = std::bind(&Processor::LD_L_H, this);
	opcodes[0x6D] = std::bind(&Processor::LD_L_L, this);
	opcodes[0x6E] = std::bind(&Processor::LD_L_MEM_HL, this);
	opcodes[0x6F] = std::bind(&Processor::LD_L_A, this);
	opcodes[0x70] = std::bind(&Processor::LD_MEM_HL_B, this);
	opcodes[0x71] = std::bind(&Processor::LD_MEM_HL_C, this);
	opcodes[0x72] = std::bind(&Processor::LD_MEM_HL_D, this);
	opcodes[0x73] = std::bind(&Processor::LD_MEM_HL_E, this);
	opcodes[0x74] = std::bind(&Processor::LD_MEM_HL_H, this);
	opcodes[0x75] = std::bind(&Processor::LD_MEM_HL_L, this);
	opcodes[0x76] = std::bind(&Processor::HALT, this);
	opcodes[0x77] = std::bind(&Processor::LD_MEM_HL_A, this);
	opcodes[0x78] = std::bind(&Processor::LD_A_B, this);
	opcodes[0x79] = std::bind(&Processor::LD_A_C, this);
	opcodes[0x7A] = std::bind(&Processor::LD_A_D, this);
	opcodes[0x7B] = std::bind(&Processor::LD_A_E, this);
	opcodes[0x7C] = std::bind(&Processor::LD_A_H, this);
	opcodes[0x7D] = std::bind(&Processor::LD_A_L, this);
	opcodes[0x7E] = std::bind(&Processor::LD_A_MEM_HL, this);
	opcodes[0x7F] = std::bind(&Processor::LD_A_A, this);
	opcodes[0x80] = std::bind(&Processor::ADD_A_B, this);
	opcodes[0x81] = std::bind(&Processor::ADD_A_C, this);
	opcodes[0x82] = std::bind(&Processor::ADD_A_D, this);
	opcodes[0x83] = std::bind(&Processor::ADD_A_E, this);
	opcodes[0x84] = std::bind(&Processor::ADD_A_H, this);
	opcodes[0x85] = std::bind(&Processor::ADD_A_L, this);
	opcodes[0x86] = std::bind(&Processor::ADD_A_MEM_HL, this);
	opcodes[0x87] = std::bind(&Processor::ADD_A_A, this);
	opcodes[0x88] = std::bind(&Processor::ADC_A_B, this);
	opcodes[0x89] = std::bind(&Processor::ADC_A_C, this);
	opcodes[0x8A] = std::bind(&Processor::ADC_A_D, this);
	opcodes[0x8B] = std::bind(&Processor::ADC_A_E, this);
	opcodes[0x8C] = std::bind(&Processor::ADC_A_H, this);
	opcodes[0x8D] = std::bind(&Processor::ADC_A_L, this);
	opcodes[0x8E] = std::bind(&Processor::ADC_A_MEM_HL, this);
	opcodes[0x8F] = std::bind(&Processor::ADC_A_A, this);
	opcodes[0x90] = std::bind(&Processor::SUB_B, this);
	opcodes[0x91] = std::bind(&Processor::SUB_C, this);
	opcodes[0x92] = std::bind(&Processor::SUB_D, this);
	opcodes[0x93] = std::bind(&Processor::SUB_E, this);
	opcodes[0x94] = std::bind(&Processor::SUB_H, this);
	opcodes[0x95] = std::bind(&Processor::SUB_L, this);
	opcodes[0x96] = std::bind(&Processor::SUB_MEM_HL, this);
	opcodes[0x97] = std::bind(&Processor::SUB_A, this);
	opcodes[0x98] = std::bind(&Processor::SBC_A_B, this);
	opcodes[0x99] = std::bind(&Processor::SBC_A_C, this);
	opcodes[0x9A] = std::bind(&Processor::SBC_A_D, this);
	opcodes[0x9B] = std::bind(&Processor::SBC_A_E, this);
	opcodes[0x9C] = std::bind(&Processor::SBC_A_H, this);
	opcodes[0x9D] = std::bind(&Processor::SBC_A_L, this);
	opcodes[0x9E] = std::bind(&Processor::SBC_A_MEM_HL, this);
	opcodes[0x9F] = std::bind(&Processor::SBC_A_A, this);
	opcodes[0xA0] = std::bind(&Processor::AND_B, this);
	opcodes[0xA1] = std::bind(&Processor::AND_C, this);
	opcodes[0xA2] = std::bind(&Processor::AND_D, this);
	opcodes[0xA3] = std::bind(&Processor::AND_E, this);
	opcodes[0xA4] = std::bind(&Processor::AND_H, this);
	opcodes[0xA5] = std::bind(&Processor::AND_L, this);
	opcodes[0xA6] = std::bind(&Processor::AND_MEM_HL, this);
	opcodes[0xA7] = std::bind(&Processor::AND_A, this);
	opcodes[0xA8] = std::bind(&Processor::XOR_B, this);
	opcodes[0xA9] = std::bind(&Processor::XOR_C, this);
	opcodes[0xAA] = std::bind(&Processor::XOR_D, this);
	opcodes[0xAB] = std::bind(&Processor::XOR_E, this);
	opcodes[0xAC] = std::bind(&Processor::XOR_H, this);
	opcodes[0xAD] = std::bind(&Processor::XOR_L, this);
	opcodes[0xAE] = std::bind(&Processor::XOR_MEM_HL, this);
	opcodes[0xAF] = std::bind(&Processor::XOR_A, this);
	opcodes[0xB0] = std::bind(&Processor::OR_B, this);
	opcodes[0xB1] = std::bind(&Processor::OR_C, this);
	opcodes[0xB2] = std::bind(&Processor::OR_D, this);
	opcodes[0xB3] = std::bind(&Processor::OR_E, this);
	opcodes[0xB4] = std::bind(&Processor::OR_H, this);
	opcodes[0xB5] = std::bind(&Processor::OR_L, this);
	opcodes[0xB6] = std::bind(&Processor::OR_MEM_HL, this);
	opcodes[0xB7] = std::bind(&Processor::OR_A, this);
	opcodes[0xB8] = std::bind(&Processor::CP_B, this);
	opcodes[0xB9] = std::bind(&Processor::CP_C, this);
	opcodes[0xBA] = std::bind(&Processor::CP_D, this);
	opcodes[0xBB] = std::bind(&Processor::CP_E, this);
	opcodes[0xBC] = std::bind(&Processor::CP_H, this);
	opcodes[0xBD] = std::bind(&Processor::CP_L, this);
	opcodes[0xBE] = std::bind(&Processor::CP_MEM_HL, this);
	opcodes[0xBF] = std::bind(&Processor::CP_A, this);
	opcodes[0xC0] = std::bind(&Processor::RET_NZ, this);
	opcodes[0xC1] = std::bind(&Processor::POP_BC, this);
	opcodes[0xC2] = std::bind(&Processor::JP_NZ_nn, this);
	opcodes[0xC3] = std::bind(&Processor::JP_nn, this);
	opcodes[0xC4] = std::bind(&Processor::CALL_NZ_nn, this);
	opcodes[0xC5] = std::bind(&Processor::PUSH_BC, this);
	opcodes[0xC6] = std::bind(&Processor::ADD_A_n, this);
	opcodes[0xC7] = std::bind(&Processor::RST, this);
	opcodes[0xC8] = std::bind(&Processor::RET_Z, this);
	opcodes[0xC9] = std::bind(&Processor::RET, this);
	opcodes[0xCA] = std::bind(&Processor::JP_Z_nn, this);
	opcodes[0xCB] = std::bind(&Processor::InvalidOpcode, this);
	opcodes[0xCC] = std::bind(&Processor::CALL_Z_nn, this);
	opcodes[0xCD] = std::bind(&Processor::CALL_nn, this);
	opcodes[0xCE] = std::bind(&Processor::ADC_A_n, this);
	opcodes[0xCF] = std::bind(&Processor::RST_0x0008, this);
	opcodes[0xD0] = std::bind(&Processor::RET_NC, this);
	opcodes[0xD1] = std::bind(&Processor::POP_DE, this);
	opcodes[0xD2] = std::bind(&Processor::JP_NC_nn, this);
	opcodes[0xD3] = std::bind(&Processor::InvalidOpcode, this);
	opcodes[0xD4] = std::bind(&Processor::CALL_NC_nn, this);
	opcodes[0xD5] = std::bind(&Processor::PUSH_DE, this);
	opcodes[0xD6] = std::bind(&Processor::SUB_n, this);
	opcodes[0xD7] = std::bind(&Processor::RST_0x0010, this);
	opcodes[0xD8] = std::bind(&Processor::RET_C, this);
	opcodes[0xD9] = std::bind(&Processor::RETI, this);
	opcodes[0xDA] = std::bind(&Processor::JP_C_nn, this);
	opcodes[0xDB] = std::bind(&Processor::InvalidOpcode, this);
	opcodes[0xDC] = std::bind(&Processor::CALL_C_nn, this);
	opcodes[0xDD] = std::bind(&Processor::InvalidOpcode, this);
	opcodes[0xDE] = std::bind(&Processor::SBC_A_n, this);
	opcodes[0xDF] = std::bind(&Processor::RST_0x0018, this);
	opcodes[0xE0] = std::bind(&Processor::LD_MEM_0xFF00_n_A, this);
	opcodes[0xE1] = std::bind(&Processor::POP_HL, this);
	opcodes[0xE2] = std::bind(&Processor::LD_MEM_0xFF00_C_A, this);
	opcodes[0xE3] = std::bind(&Processor::InvalidOpcode, this);
	opcodes[0xE4] = std::bind(&Processor::InvalidOpcode, this);
	opcodes[0xE5] = std::bind(&Processor::PUSH_HL, this);
	opcodes[0xE6] = std::bind(&Processor::AND_n, this);
	opcodes[0xE7] = std::bind(&Processor::RST_0x0020, this);
	opcodes[0xE8] = std::bind(&Processor::ADD_SP_n, this);
	opcodes[0xE9] = std::bind(&Processor::JP_MEM_HL, this);
	opcodes[0xEA] = std::bind(&Processor::LD_MEM_nn_A, this);
	opcodes[0xEB] = std::bind(&Processor::InvalidOpcode, this);
	opcodes[0xEC] = std::bind(&Processor::InvalidOpcode, this);
	opcodes[0xED] = std::bind(&Processor::InvalidOpcode, this);
	opcodes[0xEE] = std::bind(&Processor::XOR_n, this);
	opcodes[0xEF] = std::bind(&Processor::RST_0x0028, this);
	opcodes[0xF0] = std::bind(&Processor::LD_A_MEM_0xFF00_n, this);
	opcodes[0xF1] = std::bind(&Processor::POP_AF, this);
	opcodes[0xF2] = std::bind(&Processor::LD_A_MEM_0xFF00_C, this);
	opcodes[0xF3] = std::bind(&Processor::DI, this);
	opcodes[0xF4] = std::bind(&Processor::InvalidOpcode, this);
	opcodes[0xF5] = std::bind(&Processor::PUSH_AF, this);
	opcodes[0xF6] = std::bind(&Processor::OR_n, this);
	opcodes[0xF7] = std::bind(&Processor::RST_0x0030, this);
	opcodes[0xF8] = std::bind(&Processor::LD_HL_SP_n, this);
	opcodes[0xF9] = std::bind(&Processor::LD_SP_HL, this);
	opcodes[0xFA] = std::bind(&Processor::LD_A_MEM_nn, this);
	opcodes[0xFB] = std::bind(&Processor::EI, this);
	opcodes[0xFC] = std::bind(&Processor::InvalidOpcode, this);
	opcodes[0xFD] = std::bind(&Processor::InvalidOpcode, this);
	opcodes[0xFE] = std::bind(&Processor::CP_n, this);
	opcodes[0xFF] = std::bind(&Processor::RST_0x0038, this);

	// CB Obcodes
	opcodesCB[0x00] = std::bind(&Processor::RLC_B, this);
	opcodesCB[0x01] = std::bind(&Processor::RLC_C, this);
	opcodesCB[0x02] = std::bind(&Processor::RLC_D, this);
	opcodesCB[0x03] = std::bind(&Processor::RLC_E, this);
	opcodesCB[0x04] = std::bind(&Processor::RLC_H, this);
	opcodesCB[0x05] = std::bind(&Processor::RLC_L, this);
	opcodesCB[0x06] = std::bind(&Processor::RLC_MEM_HL, this);
	opcodesCB[0x07] = std::bind(&Processor::RLC_A, this);
	opcodesCB[0x08] = std::bind(&Processor::RRC_B, this);
	opcodesCB[0x09] = std::bind(&Processor::RRC_C, this);
	opcodesCB[0x0A] = std::bind(&Processor::RRC_D, this);
	opcodesCB[0x0B] = std::bind(&Processor::RRC_E, this);
	opcodesCB[0x0C] = std::bind(&Processor::RRC_H, this);
	opcodesCB[0x0D] = std::bind(&Processor::RRC_L, this);
	opcodesCB[0x0E] = std::bind(&Processor::RRC_MEM_HL, this);
	opcodesCB[0x0F] = std::bind(&Processor::RRC_A, this);
	opcodesCB[0x10] = std::bind(&Processor::RL_B, this);
	opcodesCB[0x11] = std::bind(&Processor::RL_C, this);
	opcodesCB[0x12] = std::bind(&Processor::RL_D, this);
	opcodesCB[0x13] = std::bind(&Processor::RL_E, this);
	opcodesCB[0x14] = std::bind(&Processor::RL_H, this);
	opcodesCB[0x15] = std::bind(&Processor::RL_L, this);
	opcodesCB[0x16] = std::bind(&Processor::RL_MEM_HL, this);
	opcodesCB[0x17] = std::bind(&Processor::RL_A, this);
	opcodesCB[0x18] = std::bind(&Processor::RR_B, this);
	opcodesCB[0x19] = std::bind(&Processor::RR_C, this);
	opcodesCB[0x1A] = std::bind(&Processor::RR_D, this);
	opcodesCB[0x1B] = std::bind(&Processor::RR_E, this);
	opcodesCB[0x1C] = std::bind(&Processor::RR_H, this);
	opcodesCB[0x1D] = std::bind(&Processor::RR_L, this);
	opcodesCB[0x1E] = std::bind(&Processor::RR_MEM_HL, this);
	opcodesCB[0x1F] = std::bind(&Processor::RR_A, this);
	opcodesCB[0x20] = std::bind(&Processor::SLA_B, this);
	opcodesCB[0x21] = std::bind(&Processor::SLA_C, this);
	opcodesCB[0x22] = std::bind(&Processor::SLA_D, this);
	opcodesCB[0x23] = std::bind(&Processor::SLA_E, this);
	opcodesCB[0x24] = std::bind(&Processor::SLA_H, this);
	opcodesCB[0x25] = std::bind(&Processor::SLA_L, this);
	opcodesCB[0x26] = std::bind(&Processor::SLA_MEM_HL, this);
	opcodesCB[0x27] = std::bind(&Processor::SLA_A, this);
	opcodesCB[0x28] = std::bind(&Processor::SRA_B, this);
	opcodesCB[0x29] = std::bind(&Processor::SRA_C, this);
	opcodesCB[0x2A] = std::bind(&Processor::SRA_D, this);
	opcodesCB[0x2B] = std::bind(&Processor::SRA_E, this);
	opcodesCB[0x2C] = std::bind(&Processor::SRA_H, this);
	opcodesCB[0x2D] = std::bind(&Processor::SRA_L, this);
	opcodesCB[0x2E] = std::bind(&Processor::SRA_MEM_HL, this);
	opcodesCB[0x2F] = std::bind(&Processor::SRA_A, this);
	opcodesCB[0x30] = std::bind(&Processor::SWAP_B, this);
	opcodesCB[0x31] = std::bind(&Processor::SWAP_C, this);
	opcodesCB[0x32] = std::bind(&Processor::SWAP_D, this);
	opcodesCB[0x33] = std::bind(&Processor::SWAP_E, this);
	opcodesCB[0x34] = std::bind(&Processor::SWAP_H, this);
	opcodesCB[0x35] = std::bind(&Processor::SWAP_L, this);
	opcodesCB[0x36] = std::bind(&Processor::SWAP_MEM_HL, this);
	opcodesCB[0x37] = std::bind(&Processor::SWAP_A, this);
	opcodesCB[0x38] = std::bind(&Processor::SRL_B, this);
	opcodesCB[0x39] = std::bind(&Processor::SRL_C, this);
	opcodesCB[0x3A] = std::bind(&Processor::SRL_D, this);
	opcodesCB[0x3B] = std::bind(&Processor::SRL_E, this);
	opcodesCB[0x3C] = std::bind(&Processor::SRL_H, this);
	opcodesCB[0x3D] = std::bind(&Processor::SRL_L, this);
	opcodesCB[0x3E] = std::bind(&Processor::SRL_MEM_HL, this);
	opcodesCB[0x3F] = std::bind(&Processor::SRL_A, this);
	opcodesCB[0x40] = std::bind(&Processor::BIT_0_B, this);
	opcodesCB[0x41] = std::bind(&Processor::BIT_0_C, this);
	opcodesCB[0x42] = std::bind(&Processor::BIT_0_D, this);
	opcodesCB[0x43] = std::bind(&Processor::BIT_0_E, this);
	opcodesCB[0x44] = std::bind(&Processor::BIT_0_H, this);
	opcodesCB[0x45] = std::bind(&Processor::BIT_0_L, this);
	opcodesCB[0x46] = std::bind(&Processor::BIT_0_MEM_HL, this);
	opcodesCB[0x47] = std::bind(&Processor::BIT_0_A, this);
	opcodesCB[0x48] = std::bind(&Processor::BIT_1_B, this);
	opcodesCB[0x49] = std::bind(&Processor::BIT_1_C, this);
	opcodesCB[0x4A] = std::bind(&Processor::BIT_1_D, this);
	opcodesCB[0x4B] = std::bind(&Processor::BIT_1_E, this);
	opcodesCB[0x4C] = std::bind(&Processor::BIT_1_H, this);
	opcodesCB[0x4D] = std::bind(&Processor::BIT_1_L, this);
	opcodesCB[0x4E] = std::bind(&Processor::BIT_1_MEM_HL, this);
	opcodesCB[0x4F] = std::bind(&Processor::BIT_1_A, this);
	opcodesCB[0x50] = std::bind(&Processor::BIT_2_B, this);
	opcodesCB[0x51] = std::bind(&Processor::BIT_2_C, this);
	opcodesCB[0x52] = std::bind(&Processor::BIT_2_D, this);
	opcodesCB[0x53] = std::bind(&Processor::BIT_2_E, this);
	opcodesCB[0x54] = std::bind(&Processor::BIT_2_H, this);
	opcodesCB[0x55] = std::bind(&Processor::BIT_2_L, this);
	opcodesCB[0x56] = std::bind(&Processor::BIT_2_MEM_HL, this);
	opcodesCB[0x57] = std::bind(&Processor::BIT_2_A, this);
	opcodesCB[0x58] = std::bind(&Processor::BIT_3_B, this);
	opcodesCB[0x59] = std::bind(&Processor::BIT_3_C, this);
	opcodesCB[0x5A] = std::bind(&Processor::BIT_3_D, this);
	opcodesCB[0x5B] = std::bind(&Processor::BIT_3_E, this);
	opcodesCB[0x5C] = std::bind(&Processor::BIT_3_H, this);
	opcodesCB[0x5D] = std::bind(&Processor::BIT_3_L, this);
	opcodesCB[0x5E] = std::bind(&Processor::BIT_3_MEM_HL, this);
	opcodesCB[0x5F] = std::bind(&Processor::BIT_3_A, this);
	opcodesCB[0x60] = std::bind(&Processor::BIT_4_B, this);
	opcodesCB[0x61] = std::bind(&Processor::BIT_4_C, this);
	opcodesCB[0x62] = std::bind(&Processor::BIT_4_D, this);
	opcodesCB[0x63] = std::bind(&Processor::BIT_4_E, this);
	opcodesCB[0x64] = std::bind(&Processor::BIT_4_H, this);
	opcodesCB[0x65] = std::bind(&Processor::BIT_4_L, this);
	opcodesCB[0x66] = std::bind(&Processor::BIT_4_MEM_HL, this);
	opcodesCB[0x67] = std::bind(&Processor::BIT_4_A, this);
	opcodesCB[0x68] = std::bind(&Processor::BIT_5_B, this);
	opcodesCB[0x69] = std::bind(&Processor::BIT_5_C, this);
	opcodesCB[0x6A] = std::bind(&Processor::BIT_5_D, this);
	opcodesCB[0x6B] = std::bind(&Processor::BIT_5_E, this);
	opcodesCB[0x6C] = std::bind(&Processor::BIT_5_H, this);
	opcodesCB[0x6D] = std::bind(&Processor::BIT_5_L, this);
	opcodesCB[0x6E] = std::bind(&Processor::BIT_5_MEM_HL, this);
	opcodesCB[0x6F] = std::bind(&Processor::BIT_5_A, this);
	opcodesCB[0x70] = std::bind(&Processor::BIT_6_B, this);
	opcodesCB[0x71] = std::bind(&Processor::BIT_6_C, this);
	opcodesCB[0x72] = std::bind(&Processor::BIT_6_D, this);
	opcodesCB[0x73] = std::bind(&Processor::BIT_6_E, this);
	opcodesCB[0x74] = std::bind(&Processor::BIT_6_H, this);
	opcodesCB[0x75] = std::bind(&Processor::BIT_6_L, this);
	opcodesCB[0x76] = std::bind(&Processor::BIT_6_MEM_HL, this);
	opcodesCB[0x77] = std::bind(&Processor::BIT_6_A, this);
	opcodesCB[0x78] = std::bind(&Processor::BIT_7_B, this);
	opcodesCB[0x79] = std::bind(&Processor::BIT_7_C, this);
	opcodesCB[0x7A] = std::bind(&Processor::BIT_7_D, this);
	opcodesCB[0x7B] = std::bind(&Processor::BIT_7_E, this);
	opcodesCB[0x7C] = std::bind(&Processor::BIT_7_H, this);
	opcodesCB[0x7D] = std::bind(&Processor::BIT_7_L, this);
	opcodesCB[0x7E] = std::bind(&Processor::BIT_7_MEM_HL, this);
	opcodesCB[0x7F] = std::bind(&Processor::BIT_7_A, this);
	opcodesCB[0x80] = std::bind(&Processor::RES_0_B, this);
	opcodesCB[0x81] = std::bind(&Processor::RES_0_C, this);
	opcodesCB[0x82] = std::bind(&Processor::RES_0_D, this);
	opcodesCB[0x83] = std::bind(&Processor::RES_0_E, this);
	opcodesCB[0x84] = std::bind(&Processor::RES_0_H, this);
	opcodesCB[0x85] = std::bind(&Processor::RES_0_L, this);
	opcodesCB[0x86] = std::bind(&Processor::RES_0_MEM_HL, this);
	opcodesCB[0x87] = std::bind(&Processor::RES_0_A, this);
	opcodesCB[0x88] = std::bind(&Processor::RES_1_B, this);
	opcodesCB[0x89] = std::bind(&Processor::RES_1_C, this);
	opcodesCB[0x8A] = std::bind(&Processor::RES_1_D, this);
	opcodesCB[0x8B] = std::bind(&Processor::RES_1_E, this);
	opcodesCB[0x8C] = std::bind(&Processor::RES_1_H, this);
	opcodesCB[0x8D] = std::bind(&Processor::RES_1_L, this);
	opcodesCB[0x8E] = std::bind(&Processor::RES_1_MEM_HL, this);
	opcodesCB[0x8F] = std::bind(&Processor::RES_1_A, this);
	opcodesCB[0x90] = std::bind(&Processor::RES_2_B, this);
	opcodesCB[0x91] = std::bind(&Processor::RES_2_C, this);
	opcodesCB[0x92] = std::bind(&Processor::RES_2_D, this);
	opcodesCB[0x93] = std::bind(&Processor::RES_2_E, this);
	opcodesCB[0x94] = std::bind(&Processor::RES_2_H, this);
	opcodesCB[0x95] = std::bind(&Processor::RES_2_L, this);
	opcodesCB[0x96] = std::bind(&Processor::RES_2_MEM_HL, this);
	opcodesCB[0x97] = std::bind(&Processor::RES_2_A, this);
	opcodesCB[0x98] = std::bind(&Processor::RES_3_B, this);
	opcodesCB[0x99] = std::bind(&Processor::RES_3_C, this);
	opcodesCB[0x9A] = std::bind(&Processor::RES_3_D, this);
	opcodesCB[0x9B] = std::bind(&Processor::RES_3_E, this);
	opcodesCB[0x9C] = std::bind(&Processor::RES_3_H, this);
	opcodesCB[0x9D] = std::bind(&Processor::RES_3_L, this);
	opcodesCB[0x9E] = std::bind(&Processor::RES_3_MEM_HL, this);
	opcodesCB[0x9F] = std::bind(&Processor::RES_3_A, this);
	opcodesCB[0xA0] = std::bind(&Processor::RES_4_B, this);
	opcodesCB[0xA1] = std::bind(&Processor::RES_4_C, this);
	opcodesCB[0xA2] = std::bind(&Processor::RES_4_D, this);
	opcodesCB[0xA3] = std::bind(&Processor::RES_4_E, this);
	opcodesCB[0xA4] = std::bind(&Processor::RES_4_H, this);
	opcodesCB[0xA5] = std::bind(&Processor::RES_4_L, this);
	opcodesCB[0xA6] = std::bind(&Processor::RES_4_MEM_HL, this);
	opcodesCB[0xA7] = std::bind(&Processor::RES_4_A, this);
	opcodesCB[0xA8] = std::bind(&Processor::RES_5_B, this);
	opcodesCB[0xA9] = std::bind(&Processor::RES_5_C, this);
	opcodesCB[0xAA] = std::bind(&Processor::RES_5_D, this);
	opcodesCB[0xAB] = std::bind(&Processor::RES_5_E, this);
	opcodesCB[0xAC] = std::bind(&Processor::RES_5_H, this);
	opcodesCB[0xAD] = std::bind(&Processor::RES_5_L, this);
	opcodesCB[0xAE] = std::bind(&Processor::RES_5_MEM_HL, this);
	opcodesCB[0xAF] = std::bind(&Processor::RES_5_A, this);
	opcodesCB[0xB0] = std::bind(&Processor::RES_6_B, this);
	opcodesCB[0xB1] = std::bind(&Processor::RES_6_C, this);
	opcodesCB[0xB2] = std::bind(&Processor::RES_6_D, this);
	opcodesCB[0xB3] = std::bind(&Processor::RES_6_E, this);
	opcodesCB[0xB4] = std::bind(&Processor::RES_6_H, this);
	opcodesCB[0xB5] = std::bind(&Processor::RES_6_L, this);
	opcodesCB[0xB6] = std::bind(&Processor::RES_6_MEM_HL, this);
	opcodesCB[0xB7] = std::bind(&Processor::RES_6_A, this);
	opcodesCB[0xB8] = std::bind(&Processor::RES_7_B, this);
	opcodesCB[0xB9] = std::bind(&Processor::RES_7_C, this);
	opcodesCB[0xBA] = std::bind(&Processor::RES_7_D, this);
	opcodesCB[0xBB] = std::bind(&Processor::RES_7_E, this);
	opcodesCB[0xBC] = std::bind(&Processor::RES_7_H, this);
	opcodesCB[0xBD] = std::bind(&Processor::RES_7_L, this);
	opcodesCB[0xBE] = std::bind(&Processor::RES_7_MEM_HL, this);
	opcodesCB[0xBF] = std::bind(&Processor::RES_7_A, this);
	opcodesCB[0xC0] = std::bind(&Processor::SET_0_B, this);
	opcodesCB[0xC1] = std::bind(&Processor::SET_0_C, this);
	opcodesCB[0xC2] = std::bind(&Processor::SET_0_D, this);
	opcodesCB[0xC3] = std::bind(&Processor::SET_0_E, this);
	opcodesCB[0xC4] = std::bind(&Processor::SET_0_H, this);
	opcodesCB[0xC5] = std::bind(&Processor::SET_0_L, this);
	opcodesCB[0xC6] = std::bind(&Processor::SET_0_MEM_HL, this);
	opcodesCB[0xC7] = std::bind(&Processor::SET_0_A, this);
	opcodesCB[0xC8] = std::bind(&Processor::SET_1_B, this);
	opcodesCB[0xC9] = std::bind(&Processor::SET_1_C, this);
	opcodesCB[0xCA] = std::bind(&Processor::SET_1_D, this);
	opcodesCB[0xCB] = std::bind(&Processor::SET_1_E, this);
	opcodesCB[0xCC] = std::bind(&Processor::SET_1_H, this);
	opcodesCB[0xCD] = std::bind(&Processor::SET_1_L, this);
	opcodesCB[0xCE] = std::bind(&Processor::SET_1_MEM_HL, this);
	opcodesCB[0xCF] = std::bind(&Processor::SET_1_A, this);
	opcodesCB[0xD0] = std::bind(&Processor::SET_2_B, this);
	opcodesCB[0xD1] = std::bind(&Processor::SET_2_C, this);
	opcodesCB[0xD2] = std::bind(&Processor::SET_2_D, this);
	opcodesCB[0xD3] = std::bind(&Processor::SET_2_E, this);
	opcodesCB[0xD4] = std::bind(&Processor::SET_2_H, this);
	opcodesCB[0xD5] = std::bind(&Processor::SET_2_L, this);
	opcodesCB[0xD6] = std::bind(&Processor::SET_2_MEM_HL, this);
	opcodesCB[0xD7] = std::bind(&Processor::SET_2_A, this);
	opcodesCB[0xD8] = std::bind(&Processor::SET_3_B, this);
	opcodesCB[0xD9] = std::bind(&Processor::SET_3_C, this);
	opcodesCB[0xDA] = std::bind(&Processor::SET_3_D, this);
	opcodesCB[0xDB] = std::bind(&Processor::SET_3_E, this);
	opcodesCB[0xDC] = std::bind(&Processor::SET_3_H, this);
	opcodesCB[0xDD] = std::bind(&Processor::SET_3_L, this);
	opcodesCB[0xDE] = std::bind(&Processor::SET_3_MEM_HL, this);
	opcodesCB[0xDF] = std::bind(&Processor::SET_3_A, this);
	opcodesCB[0xE0] = std::bind(&Processor::SET_4_B, this);
	opcodesCB[0xE1] = std::bind(&Processor::SET_4_C, this);
	opcodesCB[0xE2] = std::bind(&Processor::SET_4_D, this);
	opcodesCB[0xE3] = std::bind(&Processor::SET_4_E, this);
	opcodesCB[0xE4] = std::bind(&Processor::SET_4_H, this);
	opcodesCB[0xE5] = std::bind(&Processor::SET_4_L, this);
	opcodesCB[0xE6] = std::bind(&Processor::SET_4_MEM_HL, this);
	opcodesCB[0xE7] = std::bind(&Processor::SET_4_A, this);
	opcodesCB[0xE8] = std::bind(&Processor::SET_5_B, this);
	opcodesCB[0xE9] = std::bind(&Processor::SET_5_C, this);
	opcodesCB[0xEA] = std::bind(&Processor::SET_5_D, this);
	opcodesCB[0xEB] = std::bind(&Processor::SET_5_E, this);
	opcodesCB[0xEC] = std::bind(&Processor::SET_5_H, this);
	opcodesCB[0xED] = std::bind(&Processor::SET_5_L, this);
	opcodesCB[0xEE] = std::bind(&Processor::SET_5_MEM_HL, this);
	opcodesCB[0xEF] = std::bind(&Processor::SET_5_A, this);
	opcodesCB[0xF0] = std::bind(&Processor::SET_6_B, this);
	opcodesCB[0xF1] = std::bind(&Processor::SET_6_C, this);
	opcodesCB[0xF2] = std::bind(&Processor::SET_6_D, this);
	opcodesCB[0xF3] = std::bind(&Processor::SET_6_E, this);
	opcodesCB[0xF4] = std::bind(&Processor::SET_6_H, this);
	opcodesCB[0xF5] = std::bind(&Processor::SET_6_L, this);
	opcodesCB[0xF6] = std::bind(&Processor::SET_6_MEM_HL, this);
	opcodesCB[0xF7] = std::bind(&Processor::SET_6_A, this);
	opcodesCB[0xF8] = std::bind(&Processor::SET_7_B, this);
	opcodesCB[0xF9] = std::bind(&Processor::SET_7_C, this);
	opcodesCB[0xFA] = std::bind(&Processor::SET_7_D, this);
	opcodesCB[0xFB] = std::bind(&Processor::SET_7_E, this);
	opcodesCB[0xFC] = std::bind(&Processor::SET_7_H, this);
	opcodesCB[0xFD] = std::bind(&Processor::SET_7_L, this);
	opcodesCB[0xFE] = std::bind(&Processor::SET_7_MEM_HL, this);
	opcodesCB[0xFF] = std::bind(&Processor::SET_7_A, this);
}

/* NOP */
unsigned int Processor::NOP() // 0x00
{

	return 4;
}

/* LD BC, nn */
unsigned int Processor::LD_BC_nn() // 0x01
{
	BC = memory->ReadWord(PC);
	PC += 2;

	return 12;
}

/* LD (BC), A */
unsigned int Processor::LD_MEM_BC_A() // 0x02
{
	memory->WriteByte(BC, A);

	return 8;
}

/* INC BC */
unsigned int Processor::INC_BC() // 0x03
{
	BC++;

	return 8;
}

/* INC B */
unsigned int Processor::INC_B() // 0x04
{
	B = Inc(B);

	return 4;
}

/* DEC B */
unsigned int Processor::DEC_B() // 0x05
{
	B = Dec(B);

	return 4;
}

/* LD B, n */
unsigned int Processor::LD_B_n() // 0x06
{
	B = memory->ReadByte(PC++);

	return 8;
}

/* RLCA */
unsigned int Processor::RLCA() // 0x07
{
	A = Rlc(A, true);

	return 4;
}

/* LD (nn), SP */
unsigned int Processor::LD_MEM_nn_SP() // 0x08
{
	memory->WriteWord(memory->ReadWord(PC), SP);
	PC += 2;

	return 20;
}

/* ADD HL, BC */
unsigned int Processor::ADD_HL_BC() // 0x09
{
	AddHL(BC);

	return 8;
}

/* LD A, (BC) */
unsigned int Processor::LD_A_MEM_BC() // 0x0A
{
	A = memory->ReadByte(BC);

	return 8;
}

/* DEC BC */
unsigned int Processor::DEC_BC() // 0x0B
{
	BC--;

	return 8;
}

/* INC C */
unsigned int Processor::INC_C() // 0x0C
{
	C = Inc(C);

	return 4;
}

/* DEC C */
unsigned int Processor::DEC_C() // 0x0D
{
	C = Dec(C);

	return 4;
}

/* LD C, n */
unsigned int Processor::LD_C_n() // 0x0E
{
	C = memory->ReadByte(PC++);

	return 8;
}

/* RRCA */
unsigned int Processor::RRCA() // 0x0F
{
	A = Rrc(A, true);

	return 4;
}

/* STOP */
unsigned int Processor::STOP() // 0x10
{
	PC++;

	return 4;
}

/* LD DE, nn */
unsigned int Processor::LD_DE_nn() // 0x11
{
	DE = memory->ReadWord(PC);
	PC += 2;

	return 12;
}

/* LD (DE), A */
unsigned int Processor::LD_MEM_DE_A() // 0x12
{
	memory->WriteByte(DE, A);

	return 8;
}

/* INC DE */
unsigned int Processor::INC_DE() // 0x13
{
	DE++;

	return 8;
}

/* INC D */
unsigned int Processor::INC_D() // 0x14
{
	D = Inc(D);

	return 4;
}

/* DEC D */
unsigned int Processor::DEC_D() // 0x15
{
	D = Dec(D);

	return 4;
}

/* LD D, n */
unsigned int Processor::LD_D_n() // 0x16
{
	D = memory->ReadByte(PC++);

	return 8;
}

/* RLA */
unsigned int Processor::RLA() // 0x17
{
	A = Rl(A, true);

	return 4;
}

/* JR n */
unsigned int Processor::JR_n() // 0x18
{
	PC += 1 + static_cast<int8>(memory->ReadByte(PC));

	return 12;
}

/* ADD HL, DE */
unsigned int Processor::ADD_HL_DE() // 0x19
{
	AddHL(DE);

	return 8;
}

/* LD A, (DE) */
unsigned int Processor::LD_A_MEM_DE() // 0x1A
{
	A = memory->ReadByte(DE);

	return 8;
}

/* DEC DE */
unsigned int Processor::DEC_DE() // 0x1B
{
	DE--;

	return 8;
}

/* INC E */
unsigned int Processor::INC_E() // 0x1C
{
	E = Inc(E);

	return 4;
}

/* DEC E */
unsigned int Processor::DEC_E() // 0x1D
{
	E = Dec(E);

	return 4;
}

/* LD E, n */
unsigned int Processor::LD_E_n() // 0x1E
{
	E = memory->ReadByte(PC++);

	return 8;
}

/* RRA */
unsigned int Processor::RRA() // 0x1F
{
	A = Rr(A, true);

	return 4;
}

/* JR NZ, n */
unsigned int Processor::JR_NZ_n() // 0x20
{
	if (!IsFlagSet(Flag::Zero))
	{
		PC += 1 + static_cast<int8>(memory->ReadByte(PC));

		return 12;
	}
	else
	{
		PC++;
	}

	return 8;
}

/* LD HL, nn */
unsigned int Processor::LD_HL_nn() // 0x21
{
	HL = memory->ReadWord(PC);
	PC += 2;

	return 12;
}

/* LD (HLI), A */
unsigned int Processor::LD_MEM_HLI_A() // 0x22
{
	memory->WriteByte(HL++, A);

	return 8;
}

/* INC HL */
unsigned int Processor::INC_HL() // 0x23
{
	HL++;

	return 8;
}

/* INC H */
unsigned int Processor::INC_H() // 0x24
{
	H = Inc(H);

	return 4;
}

/* DEC H */
unsigned int Processor::DEC_H() // 0x25
{
	H = Dec(H);

	return 4;
}

/* LD H, n */
unsigned int Processor::LD_H_n() // 0x26
{
	H = memory->ReadByte(PC++);

	return 8;
}

/* DAA */
unsigned int Processor::DAA() // 0x27
{
	int reg = A;

	if (!IsFlagSet(Flag::Sub))
	{
		if (IsFlagSet(Flag::Half_Carry) || (reg & 0xF) > 9)
		{
			reg += 0x06;
		}

		if (IsFlagSet(Flag::Carry) || (reg > 0x9F))
		{
			reg += 0x60;
		}
	}
	else
	{
		if (IsFlagSet(Flag::Half_Carry))
		{
			reg = (reg - 6) & 0xFF;
		}

		if (IsFlagSet(Flag::Carry))
		{
			reg -= 0x60;
		}
	}

	DisableFlag(Flag::Half_Carry);
	ToggleFlag(Flag::Carry, (reg & 0x100) == 0x100);

	reg &= 0xFF;
	ToggleFlag(Flag::Zero, reg == 0);

	A = static_cast<uint8>(reg);

	return 4;
}

/* JR Z, n */
unsigned int Processor::JR_Z_n() // 0x28
{
	if (IsFlagSet(Flag::Zero))
	{
		PC += 1 + static_cast<int8>(memory->ReadByte(PC));

		return 12;
	}
	else
	{
		PC++;
	}

	return 8;
}

/* ADD HL, HL */
unsigned int Processor::ADD_HL_HL() // 0x29
{
	AddHL(HL);

	return 8;
}

/* LD A, (HLI) */
unsigned int Processor::LD_A_MEM_HLI() // 0x2A
{
	A = memory->ReadByte(HL++);

	return 8;
}

/* DEC HL */
unsigned int Processor::DEC_HL() // 0x2B
{
	HL--;

	return 8;
}

/* INC L */
unsigned int Processor::INC_L() // 0x2C
{
	L = Inc(L);

	return 4;
}

/* DEC L */
unsigned int Processor::DEC_L() // 0x2D
{
	L = Dec(L);

	return 4;
}

/* LD L, n */
unsigned int Processor::LD_L_n() // 0x2E
{
	L = memory->ReadByte(PC++);

	return 8;
}

/* CPL */
unsigned int Processor::CPL() // 0x2F
{
	A = ~A;
	EnableFlag(Flag::Half_Carry);
	EnableFlag(Flag::Sub);

	return 4;
}

/* JR NC, n */
unsigned int Processor::JR_NC_n() // 0x30
{
	if (!IsFlagSet(Flag::Carry))
	{
		PC += 1 + static_cast<int8>(memory->ReadByte(PC));

		return 12;
	}
	else
	{
		PC++;
	}

	return 8;
}

/* LD SP, nn */
unsigned int Processor::LD_SP_nn() // 0x31
{
	SP = memory->ReadWord(PC);
	PC += 2;

	return 12;
}

/* LD (HLD), A */
unsigned int Processor::LD_MEM_HLD_A() // 0x32
{
	memory->WriteByte(HL--, A);

	return 8;
}

/* INC SP */
unsigned int Processor::INC_SP() // 0x33
{
	SP++;

	return 8;
}

/* INC (HL) */
unsigned int Processor::INC_MEM_HL() // 0x34
{
	memory->WriteByte(HL, Inc(memory->ReadByte(HL)));

	return 12;
}

/* DEC (HL) */
unsigned int Processor::DEC_MEM_HL() // 0x35
{
	memory->WriteByte(HL, Dec(memory->ReadByte(HL)));

	return 12;
}

/* LD (HL), n */
unsigned int Processor::LD_MEM_HL_n() // 0x36
{
	memory->WriteByte(HL, memory->ReadByte(PC++));

	return 12;
}

/* SCF */
unsigned int Processor::SCF() // 0x37
{
	EnableFlag(Flag::Carry);
	DisableFlag(Flag::Half_Carry);
	DisableFlag(Flag::Sub);

	return 4;
}

/* JR C, n */
unsigned int Processor::JR_C_n() // 0x38
{
	if (IsFlagSet(Flag::Carry))
	{
		PC += 1 + static_cast<int8>(memory->ReadByte(PC));

		return 12;
	}
	else
	{
		PC++;
	}

	return 8;
}

/* ADD HL, SP */
unsigned int Processor::ADD_HL_SP() // 0x39
{
	AddHL(SP);

	return 8;
}

/* LD A, (HLD) */
unsigned int Processor::LD_A_MEM_HLD() // 0x3A
{
	A = memory->ReadByte(HL--);

	return 8;
}

/* DEC SP */
unsigned int Processor::DEC_SP() // 0x3B
{
	SP--;

	return 8;
}

/* INC A */
unsigned int Processor::INC_A() // 0x3C
{
	A = Inc(A);

	return 4;
}

/* DEC A */
unsigned int Processor::DEC_A() // 0x3D
{
	A = Dec(A);

	return 4;
}

/* LD A, n */
unsigned int Processor::LD_A_n() // 0x3E
{
	A = memory->ReadByte(PC++);

	return 8;
}

/* CCF */
unsigned int Processor::CCF() // 0x3F
{
	InvertFlag(Flag::Carry);
	DisableFlag(Flag::Half_Carry);
	DisableFlag(Flag::Sub);

	return 4;
}

/* LD B, B */
unsigned int Processor::LD_B_B() // 0x40
{

	return 4;
}

/* LD B, C */
unsigned int Processor::LD_B_C() // 0x41
{
	B = C;

	return 4;
}

/* LD B, D */
unsigned int Processor::LD_B_D() // 0x42
{
	B = D;

	return 4;
}

/* LD B, E */
unsigned int Processor::LD_B_E() // 0x43
{
	B = E;

	return 4;
}

/* LD B, H */
unsigned int Processor::LD_B_H() // 0x44
{
	B = H;

	return 4;
}

/* LD B, L */
unsigned int Processor::LD_B_L() // 0x45
{
	B = L;

	return 4;
}

/* LD B, (HL) */
unsigned int Processor::LD_B_MEM_HL() // 0x46
{
	B = memory->ReadByte(HL);

	return 8;
}

/* LD B, A */
unsigned int Processor::LD_B_A() // 0x47
{
	B = A;

	return 4;
}

/* LD C, B */
unsigned int Processor::LD_C_B() // 0x48
{
	C = B;

	return 4;
}

/* LD C, C */
unsigned int Processor::LD_C_C() // 0x49
{

	return 4;
}

/* LD C, D */
unsigned int Processor::LD_C_D() // 0x4A
{
	C = D;

	return 4;
}

/* LD C, E */
unsigned int Processor::LD_C_E() // 0x4B
{
	C = E;

	return 4;
}

/* LD C, H */
unsigned int Processor::LD_C_H() // 0x4C
{
	C = H;

	return 4;
}

/* LD C, L */
unsigned int Processor::LD_C_L() // 0x4D
{
	C = L;

	return 4;
}

/* LD C, (HL) */
unsigned int Processor::LD_C_MEM_HL() // 0x4E
{
	C = memory->ReadByte(HL);

	return 8;
}

/* LD C, A */
unsigned int Processor::LD_C_A() // 0x4F
{
	C = A;

	return 4;
}

/* LD D, B */
unsigned int Processor::LD_D_B() // 0x50
{
	D = B;

	return 4;
}

/* LD D, C */
unsigned int Processor::LD_D_C() // 0x51
{
	D = C;

	return 4;
}

/* LD D, D */
unsigned int Processor::LD_D_D() // 0x52
{

	return 4;
}

/* LD D, E */
unsigned int Processor::LD_D_E() // 0x53
{
	D = E;

	return 4;
}

/* LD D, H */
unsigned int Processor::LD_D_H() // 0x54
{
	D = H;

	return 4;
}

/* LD D, L */
unsigned int Processor::LD_D_L() // 0x55
{
	D = L;

	return 4;
}

/* LD D, (HL) */
unsigned int Processor::LD_D_MEM_HL() // 0x56
{
	D = memory->ReadByte(HL);

	return 8;
}

/* LD D, A */
unsigned int Processor::LD_D_A() // 0x57
{
	D = A;

	return 4;
}

/* LD E, B */
unsigned int Processor::LD_E_B() // 0x58
{
	E = B;

	return 4;
}

/* LD E, C */
unsigned int Processor::LD_E_C() // 0x59
{
	E = C;

	return 4;
}

/* LD E, D */
unsigned int Processor::LD_E_D() // 0x5A
{
	E = D;

	return 4;
}

/* LD E, E */
unsigned int Processor::LD_E_E() // 0x5B
{

	return 4;
}

/* LD E, H */
unsigned int Processor::LD_E_H() // 0x5C
{
	E = H;

	return 4;
}

/* LD E, L */
unsigned int Processor::LD_E_L() // 0x5D
{
	E = L;

	return 4;
}

/* LD E, (HL) */
unsigned int Processor::LD_E_MEM_HL() // 0x5E
{
	E = memory->ReadByte(HL);

	return 8;
}

/* LD E, A */
unsigned int Processor::LD_E_A() // 0x5F
{
	E = A;

	return 4;
}

/* LD H, B */
unsigned int Processor::LD_H_B() // 0x60
{
	H = B;

	return 4;
}

/* LD H, C */
unsigned int Processor::LD_H_C() // 0x61
{
	H = C;

	return 4;
}

/* LD H, D */
unsigned int Processor::LD_H_D() // 0x62
{
	H = D;

	return 4;
}

/* LD H, E */
unsigned int Processor::LD_H_E() // 0x63
{
	H = E;

	return 4;
}

/* LD H, H */
unsigned int Processor::LD_H_H() // 0x64
{

	return 4;
}

/* LD H, L */
unsigned int Processor::LD_H_L() // 0x65
{
	H = L;

	return 4;
}

/* LD H, (HL) */
unsigned int Processor::LD_H_MEM_HL() // 0x66
{
	H = memory->ReadByte(HL);

	return 8;
}

/* LD H, A */
unsigned int Processor::LD_H_A() // 0x67
{
	H = A;

	return 4;
}

/* LD L, B */
unsigned int Processor::LD_L_B() // 0x68
{
	L = B;

	return 4;
}

/* LD L, C */
unsigned int Processor::LD_L_C() // 0x69
{
	L = C;

	return 4;
}

/* LD L, D */
unsigned int Processor::LD_L_D() // 0x6A
{
	L = D;

	return 4;
}

/* LD L, E */
unsigned int Processor::LD_L_E() // 0x6B
{
	L = E;

	return 4;
}

/* LD L, H */
unsigned int Processor::LD_L_H() // 0x6C
{
	L = H;

	return 4;
}

/* LD L, L */
unsigned int Processor::LD_L_L() // 0x6D
{

	return 4;
}

/* LD L, (HL) */
unsigned int Processor::LD_L_MEM_HL() // 0x6E
{
	L = memory->ReadByte(HL);

	return 8;
}

/* LD L, A */
unsigned int Processor::LD_L_A() // 0x6F
{
	L = A;

	return 4;
}

/* LD (HL), B */
unsigned int Processor::LD_MEM_HL_B() // 0x70
{
	memory->WriteByte(HL, B);

	return 8;
}

/* LD (HL), C */
unsigned int Processor::LD_MEM_HL_C() // 0x71
{
	memory->WriteByte(HL, C);

	return 8;
}

/* LD (HL), D */
unsigned int Processor::LD_MEM_HL_D() // 0x72
{
	memory->WriteByte(HL, D);

	return 8;
}

/* LD (HL), E */
unsigned int Processor::LD_MEM_HL_E() // 0x73
{
	memory->WriteByte(HL, E);

	return 8;
}

/* LD (HL), H */
unsigned int Processor::LD_MEM_HL_H() // 0x74
{
	memory->WriteByte(HL, H);

	return 8;
}

/* LD (HL), L */
unsigned int Processor::LD_MEM_HL_L() // 0x75
{
	memory->WriteByte(HL, L);

	return 8;
}

/* HALT */
unsigned int Processor::HALT() // 0x76
{
	halted = true;

	return 4;
}

/* LD (HL), A */
unsigned int Processor::LD_MEM_HL_A() // 0x77
{
	memory->WriteByte(HL, A);

	return 8;
}

/* LD A, B */
unsigned int Processor::LD_A_B() // 0x78
{
	A = B;

	return 4;
}

/* LD A, C */
unsigned int Processor::LD_A_C() // 0x79
{
	A = C;

	return 4;
}

/* LD A, D */
unsigned int Processor::LD_A_D() // 0x7A
{
	A = D;

	return 4;
}

/* LD A, E */
unsigned int Processor::LD_A_E() // 0x7B
{
	A = E;

	return 4;
}

/* LD A, H */
unsigned int Processor::LD_A_H() // 0x7C
{
	A = H;

	return 4;
}

/* LD A, L */
unsigned int Processor::LD_A_L() // 0x7D
{
	A = L;

	return 4;
}

/* LD A, (HL) */
unsigned int Processor::LD_A_MEM_HL() // 0x7E
{
	A = memory->ReadByte(HL);

	return 8;
}

/* LD A, A */
unsigned int Processor::LD_A_A() // 0x7F
{

	return 4;
}

/* ADD A, B */
unsigned int Processor::ADD_A_B() // 0x80
{
	Add(B);

	return 4;
}

/* ADD A, C */
unsigned int Processor::ADD_A_C() // 0x81
{
	Add(C);

	return 4;
}

/* ADD A, D */
unsigned int Processor::ADD_A_D() // 0x82
{
	Add(D);

	return 4;
}

/* ADD A, E */
unsigned int Processor::ADD_A_E() // 0x83
{
	Add(E);

	return 4;
}

/* ADD A, H */
unsigned int Processor::ADD_A_H() // 0x84
{
	Add(H);

	return 4;
}

/* ADD A, L */
unsigned int Processor::ADD_A_L() // 0x85
{
	Add(L);

	return 4;
}

/* ADD A, (HL) */
unsigned int Processor::ADD_A_MEM_HL() // 0x86
{
	Add(memory->ReadByte(HL));

	return 8;
}

/* ADD A, A */
unsigned int Processor::ADD_A_A() // 0x87
{
	Add(A);

	return 4;
}

/* ADC A, B */
unsigned int Processor::ADC_A_B() // 0x88
{
	Adc(B);

	return 4;
}

/* ADC A, C */
unsigned int Processor::ADC_A_C() // 0x89
{
	Adc(C);

	return 4;
}

/* ADC A, D */
unsigned int Processor::ADC_A_D() // 0x8A
{
	Adc(D);

	return 4;
}

/* ADC A, E */
unsigned int Processor::ADC_A_E() // 0x8B
{
	Adc(E);

	return 4;
}

/* ADC A, H */
unsigned int Processor::ADC_A_H() // 0x8C
{
	Adc(H);

	return 4;
}

/* ADC A, L */
unsigned int Processor::ADC_A_L() // 0x8D
{
	Adc(L);

	return 4;
}

/* ADC A, (HL) */
unsigned int Processor::ADC_A_MEM_HL() // 0x8E
{
	Adc(memory->ReadByte(HL));

	return 8;
}

/* ADC A, A */
unsigned int Processor::ADC_A_A() // 0x8F
{
	Adc(A);

	return 4;
}

/* SUB B */
unsigned int Processor::SUB_B() // 0x90
{
	Sub(B);

	return 4;
}

/* SUB C */
unsigned int Processor::SUB_C() // 0x91
{
	Sub(C);

	return 4;
}

/* SUB D */
unsigned int Processor::SUB_D() // 0x92
{
	Sub(D);

	return 4;
}

/* SUB E */
unsigned int Processor::SUB_E() // 0x93
{
	Sub(E);

	return 4;
}

/* SUB H */
unsigned int Processor::SUB_H() // 0x94
{
	Sub(H);

	return 4;
}

/* SUB L */
unsigned int Processor::SUB_L() // 0x95
{
	Sub(L);

	return 4;
}

/* SUB (HL) */
unsigned int Processor::SUB_MEM_HL() // 0x96
{
	Sub(memory->ReadByte(HL));

	return 8;
}

/* SUB A */
unsigned int Processor::SUB_A() // 0x97
{
	Sub(A);

	return 4;
}

/* SBC A, B */
unsigned int Processor::SBC_A_B() // 0x98
{
	Sbc(B);

	return 4;
}

/* SBC A, C */
unsigned int Processor::SBC_A_C() // 0x99
{
	Sbc(C);

	return 4;
}

/* SBC A, D */
unsigned int Processor::SBC_A_D() // 0x9A
{
	Sbc(D);

	return 4;
}

/* SBC A, E */
unsigned int Processor::SBC_A_E() // 0x9B
{
	Sbc(E);

	return 4;
}

/* SBC A, H */
unsigned int Processor::SBC_A_H() // 0x9C
{
	Sbc(H);

	return 4;
}

/* SBC A, L */
unsigned int Processor::SBC_A_L() // 0x9D
{
	Sbc(L);

	return 4;
}

/* SBC A, (HL) */
unsigned int Processor::SBC_A_MEM_HL() // 0x9E
{
	Sbc(memory->ReadByte(HL));

	return 8;
}

/* SBC A, A */
unsigned int Processor::SBC_A_A() // 0x9F
{
	Sbc(A);

	return 4;
}

/* AND B */
unsigned int Processor::AND_B() // 0xA0
{
	A &= B;
	SetFlags(Flag::Half_Carry);
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* AND C */
unsigned int Processor::AND_C() // 0xA1
{
	A &= C;
	SetFlags(Flag::Half_Carry);
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* AND D */
unsigned int Processor::AND_D() // 0xA2
{
	A &= D;
	SetFlags(Flag::Half_Carry);
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* AND E */
unsigned int Processor::AND_E() // 0xA3
{
	A &= E;
	SetFlags(Flag::Half_Carry);
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* AND H */
unsigned int Processor::AND_H() // 0xA4
{
	A &= H;
	SetFlags(Flag::Half_Carry);
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* AND L */
unsigned int Processor::AND_L() // 0xA5
{
	A &= L;
	SetFlags(Flag::Half_Carry);
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* AND (HL) */
unsigned int Processor::AND_MEM_HL() // 0xA6
{
	A &= memory->ReadByte(HL);
	SetFlags(Flag::Half_Carry);
	ToggleFlag(Flag::Zero, A == 0);

	return 8;
}

/* AND A */
unsigned int Processor::AND_A() // 0xA7
{
	A &= A;
	SetFlags(Flag::Half_Carry);
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* XOR B */
unsigned int Processor::XOR_B() // 0xA8
{
	A ^= B;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* XOR C */
unsigned int Processor::XOR_C() // 0xA9
{
	A ^= C;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* XOR D */
unsigned int Processor::XOR_D() // 0xAA
{
	A ^= D;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* XOR E */
unsigned int Processor::XOR_E() // 0xAB
{
	A ^= E;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* XOR H */
unsigned int Processor::XOR_H() // 0xAC
{
	A ^= H;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* XOR L */
unsigned int Processor::XOR_L() // 0xAD
{
	A ^= L;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* XOR (HL) */
unsigned int Processor::XOR_MEM_HL() // 0xAE
{
	A ^= memory->ReadByte(HL);
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 8;
}

/* XOR A */
unsigned int Processor::XOR_A() // 0xAF
{
	A ^= A;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* OR B */
unsigned int Processor::OR_B() // 0xB0
{
	A |= B;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* OR C */
unsigned int Processor::OR_C() // 0xB1
{
	A |= C;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* OR D */
unsigned int Processor::OR_D() // 0xB2
{
	A |= D;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* OR E */
unsigned int Processor::OR_E() // 0xB3
{
	A |= E;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* OR H */
unsigned int Processor::OR_H() // 0xB4
{
	A |= H;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* OR L */
unsigned int Processor::OR_L() // 0xB5
{
	A |= L;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* OR (HL) */
unsigned int Processor::OR_MEM_HL() // 0xB6
{
	A |= memory->ReadByte(HL);
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 8;
}

/* OR A */
unsigned int Processor::OR_A() // 0xB7
{
	A |= A;
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 4;
}

/* CP B */
unsigned int Processor::CP_B() // 0xB8
{
	uint8 value = B;
	SetFlags(Flag::Sub);
	ToggleFlag(Flag::Carry, A < value);
	ToggleFlag(Flag::Zero, A == value);
	ToggleFlag(Flag::Half_Carry, ((A - value) & 0xF) > (A & 0xF));

	return 4;
}

/* CP C */
unsigned int Processor::CP_C() // 0xB9
{
	uint8 value = C;
	SetFlags(Flag::Sub);
	ToggleFlag(Flag::Carry, A < value);
	ToggleFlag(Flag::Zero, A == value);
	ToggleFlag(Flag::Half_Carry, ((A - value) & 0xF) > (A & 0xF));

	return 4;
}

/* CP D */
unsigned int Processor::CP_D() // 0xBA
{
	uint8 value = D;
	SetFlags(Flag::Sub);
	ToggleFlag(Flag::Carry, A < value);
	ToggleFlag(Flag::Zero, A == value);
	ToggleFlag(Flag::Half_Carry, ((A - value) & 0xF) > (A & 0xF));

	return 4;
}

/* CP E */
unsigned int Processor::CP_E() // 0xBB
{
	uint8 value = E;
	SetFlags(Flag::Sub);
	ToggleFlag(Flag::Carry, A < value);
	ToggleFlag(Flag::Zero, A == value);
	ToggleFlag(Flag::Half_Carry, ((A - value) & 0xF) > (A & 0xF));

	return 4;
}

/* CP H */
unsigned int Processor::CP_H() // 0xBC
{
	uint8 value = H;
	SetFlags(Flag::Sub);
	ToggleFlag(Flag::Carry, A < value);
	ToggleFlag(Flag::Zero, A == value);
	ToggleFlag(Flag::Half_Carry, ((A - value) & 0xF) > (A & 0xF));

	return 4;
}

/* CP L */
unsigned int Processor::CP_L() // 0xBD
{
	uint8 value = L;
	SetFlags(Flag::Sub);
	ToggleFlag(Flag::Carry, A < value);
	ToggleFlag(Flag::Zero, A == value);
	ToggleFlag(Flag::Half_Carry, ((A - value) & 0xF) > (A & 0xF));

	return 4;
}

/* CP (HL) */
unsigned int Processor::CP_MEM_HL() // 0xBE
{
	uint8 value = memory->ReadByte(HL);
	SetFlags(Flag::Sub);
	ToggleFlag(Flag::Carry, A < value);
	ToggleFlag(Flag::Zero, A == value);
	ToggleFlag(Flag::Half_Carry, ((A - value) & 0xF) > (A & 0xF));

	return 8;
}

/* CP A */
unsigned int Processor::CP_A() // 0xBF
{
	uint8 value = A;
	SetFlags(Flag::Sub);
	ToggleFlag(Flag::Carry, A < value);
	ToggleFlag(Flag::Zero, A == value);
	ToggleFlag(Flag::Half_Carry, ((A - value) & 0xF) > (A & 0xF));

	return 4;
}

/* RET NZ */
unsigned int Processor::RET_NZ() // 0xC0
{
	if (!IsFlagSet(Flag::Zero))
	{
		PopFromStack(PC);

		return 20;
	}

	return 8;
}

/* POP BC */
unsigned int Processor::POP_BC() // 0xC1
{
	PopFromStack(BC);

	return 12;
}

/* JP NZ, nn */
unsigned int Processor::JP_NZ_nn() // 0xC2
{
	if (!IsFlagSet(Flag::Zero))
	{
		PC = memory->ReadWord(PC);

		return 16;
	}
	else
	{
		PC += 2;
	}

	return 12;
}

/* JP nn */
unsigned int Processor::JP_nn() // 0xC3
{
	PC = memory->ReadWord(PC);

	return 16;
}

/* CALL NZ, nn */
unsigned int Processor::CALL_NZ_nn() // 0xC4
{
	if (!IsFlagSet(Flag::Zero))
	{
		uint16 address = memory->ReadWord(PC);
		PC += 2;
		PushToStack(PC);
		PC = address;

		return 24;
	}
	else
	{
		PC += 2;
	}

	return 12;
}

/* PUSH BC */
unsigned int Processor::PUSH_BC() // 0xC5
{
	PushToStack(BC);

	return 16;
}

/* ADD A, n */
unsigned int Processor::ADD_A_n() // 0xC6
{
	Add(memory->ReadByte(PC++));

	return 8;
}

/* RST  */
unsigned int Processor::RST() // 0xC7
{
	PushToStack(PC);
	PC = 0x0000;

	return 16;
}

/* RET Z */
unsigned int Processor::RET_Z() // 0xC8
{
	if (IsFlagSet(Flag::Zero))
	{
		PopFromStack(PC);

		return 20;
	}

	return 8;
}

/* RET */
unsigned int Processor::RET() // 0xC9
{
	PopFromStack(PC);

	return 16;
}

/* JP Z, nn */
unsigned int Processor::JP_Z_nn() // 0xCA
{
	if (IsFlagSet(Flag::Zero))
	{
		PC = memory->ReadWord(PC);

		return 16;
	}
	else
	{
		PC += 2;
	}

	return 12;
}

/* CALL Z, nn */
unsigned int Processor::CALL_Z_nn() // 0xCC
{
	if (IsFlagSet(Flag::Zero))
	{
		uint16 address = memory->ReadWord(PC);
		PC += 2;
		PushToStack(PC);
		PC = address;

		return 24;
	}
	else
	{
		PC += 2;
	}

	return 12;
}

/* CALL nn */
unsigned int Processor::CALL_nn() // 0xCD
{
	uint16 address = memory->ReadWord(PC);
	PC += 2;
	PushToStack(PC);
	PC = address;

	return 24;
}

/* ADC A, n */
unsigned int Processor::ADC_A_n() // 0xCE
{
	Adc(memory->ReadByte(PC++));

	return 8;
}

/* RST 0x0008 */
unsigned int Processor::RST_0x0008() // 0xCF
{
	PushToStack(PC);
	PC = 0x0008;

	return 16;
}

/* RET NC */
unsigned int Processor::RET_NC() // 0xD0
{
	if (!IsFlagSet(Flag::Carry))
	{
		PopFromStack(PC);

		return 20;
	}

	return 8;
}

/* POP DE */
unsigned int Processor::POP_DE() // 0xD1
{
	PopFromStack(DE);

	return 12;
}

/* JP NC, nn */
unsigned int Processor::JP_NC_nn() // 0xD2
{
	if (!IsFlagSet(Flag::Carry))
	{
		PC = memory->ReadWord(PC);

		return 16;
	}
	else
	{
		PC += 2;
	}

	return 12;
}

/* CALL NC, nn */
unsigned int Processor::CALL_NC_nn() // 0xD4
{
	if (!IsFlagSet(Flag::Carry))
	{
		uint16 address = memory->ReadWord(PC);
		PC += 2;
		PushToStack(PC);
		PC = address;

		return 24;
	}
	else
	{
		PC += 2;
	}

	return 12;
}

/* PUSH DE */
unsigned int Processor::PUSH_DE() // 0xD5
{
	PushToStack(DE);

	return 16;
}

/* SUB n */
unsigned int Processor::SUB_n() // 0xD6
{
	Sub(memory->ReadByte(PC++));

	return 8;
}

/* RST 0x0010 */
unsigned int Processor::RST_0x0010() // 0xD7
{
	PushToStack(PC);
	PC = 0x0010;

	return 16;
}

/* RET C */
unsigned int Processor::RET_C() // 0xD8
{
	if (IsFlagSet(Flag::Carry))
	{
		PopFromStack(PC);

		return 20;
	}

	return 8;
}

/* RETI */
unsigned int Processor::RETI() // 0xD9
{
	PopFromStack(PC);
	ime = true;

	return 16;
}

/* JP C, nn */
unsigned int Processor::JP_C_nn() // 0xDA
{
	if (IsFlagSet(Flag::Carry))
	{
		PC = memory->ReadWord(PC);

		return 16;
	}
	else
	{
		PC += 2;
	}

	return 12;
}

/* CALL C, nn */
unsigned int Processor::CALL_C_nn() // 0xDC
{
	if (IsFlagSet(Flag::Carry))
	{
		uint16 address = memory->ReadWord(PC);
		PC += 2;
		PushToStack(PC);
		PC = address;

		return 24;
	}
	else
	{
		PC += 2;
	}

	return 12;
}

/* SBC A, n */
unsigned int Processor::SBC_A_n() // 0xDE
{
	Sbc(memory->ReadByte(PC++));

	return 8;
}

/* RST 0x0018 */
unsigned int Processor::RST_0x0018() // 0xDF
{
	PushToStack(PC);
	PC = 0x0018;

	return 16;
}

/* LD (0xFF00+n), A */
unsigned int Processor::LD_MEM_0xFF00_n_A() // 0xE0
{
	memory->WriteByte(0xFF00 + memory->ReadByte(PC++), A);

	return 12;
}

/* POP HL */
unsigned int Processor::POP_HL() // 0xE1
{
	PopFromStack(HL);

	return 12;
}

/* LD (0xFF00+C), A */
unsigned int Processor::LD_MEM_0xFF00_C_A() // 0xE2
{
	memory->WriteByte(0xFF00 + C, A);

	return 8;
}

/* PUSH HL */
unsigned int Processor::PUSH_HL() // 0xE5
{
	PushToStack(HL);

	return 16;
}

/* AND n */
unsigned int Processor::AND_n() // 0xE6
{
	A &= memory->ReadByte(PC++);
	SetFlags(Flag::Half_Carry);
	ToggleFlag(Flag::Zero, A == 0);

	return 8;
}

/* RST 0x0020 */
unsigned int Processor::RST_0x0020() // 0xE7
{
	PushToStack(PC);
	PC = 0x0020;

	return 16;
}

/* ADD SP, n */
unsigned int Processor::ADD_SP_n() // 0xE8
{
	AddSP(static_cast<int8>(memory->ReadByte(PC++)));

	return 16;
}

/* JP (HL) */
unsigned int Processor::JP_MEM_HL() // 0xE9
{
	PC = HL;

	return 4;
}

/* LD (nn), A */
unsigned int Processor::LD_MEM_nn_A() // 0xEA
{
	memory->WriteByte(memory->ReadWord(PC), A);
	PC += 2;

	return 16;
}

/* XOR n */
unsigned int Processor::XOR_n() // 0xEE
{
	A ^= memory->ReadByte(PC++);
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 8;
}

/* RST 0x0028 */
unsigned int Processor::RST_0x0028() // 0xEF
{
	PushToStack(PC);
	PC = 0x0028;

	return 16;
}

/* LD A, (0xFF00+n) */
unsigned int Processor::LD_A_MEM_0xFF00_n() // 0xF0
{
	A = memory->ReadByte(0xFF00 + memory->ReadByte(PC++));

	return 12;
}

/* POP AF */
unsigned int Processor::POP_AF() // 0xF1
{
	PopFromStack(AF);
	F &= 0xF0;

	return 12;
}

/* LD A, (0xFF00+C) */
unsigned int Processor::LD_A_MEM_0xFF00_C() // 0xF2
{
	A = memory->ReadByte(0xFF00 + C);

	return 8;
}

/* DI */
unsigned int Processor::DI() // 0xF3
{
	ime = false;

	return 4;
}

/* PUSH AF */
unsigned int Processor::PUSH_AF() // 0xF5
{
	PushToStack(AF);

	return 16;
}

/* OR n */
unsigned int Processor::OR_n() // 0xF6
{
	A |= memory->ReadByte(PC++);
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 8;
}

/* RST 0x0030 */
unsigned int Processor::RST_0x0030() // 0xF7
{
	PushToStack(PC);
	PC = 0x0030;

	return 16;
}

/* LD HL, SP+n */
unsigned int Processor::LD_HL_SP_n() // 0xF8
{
	int8 n = static_cast<int8>(memory->ReadByte(PC++));
	HL = SP + n;
	ClearFlags();
	ToggleFlag(Flag::Carry, ((SP ^ n ^ HL) & 0x100) == 0x100);
	ToggleFlag(Flag::Half_Carry, ((SP ^ n ^ HL) & 0x10) == 0x10);

	return 12;
}

/* LD SP, HL */
unsigned int Processor::LD_SP_HL() // 0xF9
{
	SP = HL;

	return 8;
}

/* LD A, (nn) */
unsigned int Processor::LD_A_MEM_nn() // 0xFA
{
	A = memory->ReadByte(memory->ReadWord(PC));
	PC += 2;

	return 16;
}

/* EI */
unsigned int Processor::EI() // 0xFB
{
	ime = true;

	return 4;
}

/* CP n */
unsigned int Processor::CP_n() // 0xFE
{
	uint8 value = memory->ReadByte(PC++);
	SetFlags(Flag::Sub);
	ToggleFlag(Flag::Carry, A < value);
	ToggleFlag(Flag::Zero, A == value);
	ToggleFlag(Flag::Half_Carry, ((A - value) & 0xF) > (A & 0xF));

	return 8;
}

/* RST 0x0038 */
unsigned int Processor::RST_0x0038() // 0xFF
{
	PushToStack(PC);
	PC = 0x0038;

	return 16;
}

// CB Obcodes

/* RLC B */
unsigned int Processor::RLC_B() // 0x00
{
	B = Rlc(B, false);

	return 8;
}

/* RLC C */
unsigned int Processor::RLC_C() // 0x01
{
	C = Rlc(C, false);

	return 8;
}

/* RLC D */
unsigned int Processor::RLC_D() // 0x02
{
	D = Rlc(D, false);

	return 8;
}

/* RLC E */
unsigned int Processor::RLC_E() // 0x03
{
	E = Rlc(E, false);

	return 8;
}

/* RLC H */
unsigned int Processor::RLC_H() // 0x04
{
	H = Rlc(H, false);

	return 8;
}

/* RLC L */
unsigned int Processor::RLC_L() // 0x05
{
	L = Rlc(L, false);

	return 8;
}

/* RLC (HL) */
unsigned int Processor::RLC_MEM_HL() // 0x06
{
	memory->WriteByte(HL, Rlc(memory->ReadByte(HL), false));

	return 16;
}

/* RLC A */
unsigned int Processor::RLC_A() // 0x07
{
	A = Rlc(A, false);

	return 8;
}

/* RRC B */
unsigned int Processor::RRC_B() // 0x08
{
	B = Rrc(B, false);

	return 8;
}

/* RRC C */
unsigned int Processor::RRC_C() // 0x09
{
	C = Rrc(C, false);

	return 8;
}

/* RRC D */
unsigned int Processor::RRC_D() // 0x0A
{
	D = Rrc(D, false);

	return 8;
}

/* RRC E */
unsigned int Processor::RRC_E() // 0x0B
{
	E = Rrc(E, false);

	return 8;
}

/* RRC H */
unsigned int Processor::RRC_H() // 0x0C
{
	H = Rrc(H, false);

	return 8;
}

/* RRC L */
unsigned int Processor::RRC_L() // 0x0D
{
	L = Rrc(L, false);

	return 8;
}

/* RRC (HL) */
unsigned int Processor::RRC_MEM_HL() // 0x0E
{
	memory->WriteByte(HL, Rrc(memory->ReadByte(HL), false));

	return 16;
}

/* RRC A */
unsigned int Processor::RRC_A() // 0x0F
{
	A = Rrc(A, false);

	return 8;
}

/* RL B */
unsigned int Processor::RL_B() // 0x10
{
	B = Rl(B, false);

	return 8;
}

/* RL C */
unsigned int Processor::RL_C() // 0x11
{
	C = Rl(C, false);

	return 8;
}

/* RL D */
unsigned int Processor::RL_D() // 0x12
{
	D = Rl(D, false);

	return 8;
}

/* RL E */
unsigned int Processor::RL_E() // 0x13
{
	E = Rl(E, false);

	return 8;
}

/* RL H */
unsigned int Processor::RL_H() // 0x14
{
	H = Rl(H, false);

	return 8;
}

/* RL L,  */
unsigned int Processor::RL_L() // 0x15
{
	L = Rl(L, false);

	return 8;
}

/* RL (HL) */
unsigned int Processor::RL_MEM_HL() // 0x16
{
	memory->WriteByte(HL, Rl(memory->ReadByte(HL), false));

	return 16;
}

/* RL A */
unsigned int Processor::RL_A() // 0x17
{
	A = Rl(A, false);

	return 8;
}

/* RR B */
unsigned int Processor::RR_B() // 0x18
{
	B = Rr(B, false);

	return 8;
}

/* RR C */
unsigned int Processor::RR_C() // 0x19
{
	C = Rr(C, false);

	return 8;
}

/* RR D */
unsigned int Processor::RR_D() // 0x1A
{
	D = Rr(D, false);

	return 8;
}

/* RR E */
unsigned int Processor::RR_E() // 0x1B
{
	E = Rr(E, false);

	return 8;
}

/* RR H */
unsigned int Processor::RR_H() // 0x1C
{
	H = Rr(H, false);

	return 8;
}

/* RR L */
unsigned int Processor::RR_L() // 0x1D
{
	L = Rr(L, false);

	return 8;
}

/* RR (HL) */
unsigned int Processor::RR_MEM_HL() // 0x1E
{
	memory->WriteByte(HL, Rr(memory->ReadByte(HL), false));

	return 16;
}

/* RR A */
unsigned int Processor::RR_A() // 0x1F
{
	A = Rr(A, false);

	return 8;
}

/* SLA B */
unsigned int Processor::SLA_B() // 0x20
{
	B = Sla(B);

	return 8;
}

/* SLA C */
unsigned int Processor::SLA_C() // 0x21
{
	C = Sla(C);

	return 8;
}

/* SLA D */
unsigned int Processor::SLA_D() // 0x22
{
	D = Sla(D);

	return 8;
}

/* SLA E */
unsigned int Processor::SLA_E() // 0x23
{
	E = Sla(E);

	return 8;
}

/* SLA H */
unsigned int Processor::SLA_H() // 0x24
{
	H = Sla(H);

	return 8;
}

/* SLA L */
unsigned int Processor::SLA_L() // 0x25
{
	L = Sla(L);

	return 8;
}

/* SLA (HL) */
unsigned int Processor::SLA_MEM_HL() // 0x26
{
	memory->WriteByte(HL, Sla(memory->ReadByte(HL)));

	return 16;
}

/* SLA A */
unsigned int Processor::SLA_A() // 0x27
{
	A = Sla(A);

	return 8;
}

/* SRA B */
unsigned int Processor::SRA_B() // 0x28
{
	B = Sra(B);

	return 8;
}

/* SRA C */
unsigned int Processor::SRA_C() // 0x29
{
	C = Sra(C);

	return 8;
}

/* SRA D */
unsigned int Processor::SRA_D() // 0x2A
{
	D = Sra(D);

	return 8;
}

/* SRA E */
unsigned int Processor::SRA_E() // 0x2B
{
	E = Sra(E);

	return 8;
}

/* SRA H */
unsigned int Processor::SRA_H() // 0x2C
{
	H = Sra(H);

	return 8;
}

/* SRA L */
unsigned int Processor::SRA_L() // 0x2D
{
	L = Sra(L);

	return 8;
}

/* SRA (HL) */
unsigned int Processor::SRA_MEM_HL() // 0x2E
{
	memory->WriteByte(HL, Sra(memory->ReadByte(HL)));

	return 16;
}

/* SRA A */
unsigned int Processor::SRA_A() // 0x2F
{
	A = Sra(A);

	return 8;
}

/* SWAP B */
unsigned int Processor::SWAP_B() // 0x30
{
	B = ((B >> 4) & 0x0F) | ((B << 4) & 0xF0);
	ClearFlags();
	ToggleFlag(Flag::Zero, B == 0);

	return 8;
}

/* SWAP C */
unsigned int Processor::SWAP_C() // 0x31
{
	C = ((C >> 4) & 0x0F) | ((C << 4) & 0xF0);
	ClearFlags();
	ToggleFlag(Flag::Zero, C == 0);

	return 8;
}

/* SWAP D */
unsigned int Processor::SWAP_D() // 0x32
{
	D = ((D >> 4) & 0x0F) | ((D << 4) & 0xF0);
	ClearFlags();
	ToggleFlag(Flag::Zero, D == 0);

	return 8;
}

/* SWAP E */
unsigned int Processor::SWAP_E() // 0x33
{
	E = ((E >> 4) & 0x0F) | ((E << 4) & 0xF0);
	ClearFlags();
	ToggleFlag(Flag::Zero, E == 0);

	return 8;
}

/* SWAP H */
unsigned int Processor::SWAP_H() // 0x34
{
	H = ((H >> 4) & 0x0F) | ((H << 4) & 0xF0);
	ClearFlags();
	ToggleFlag(Flag::Zero, H == 0);

	return 8;
}

/* SWAP L */
unsigned int Processor::SWAP_L() // 0x35
{
	L = ((L >> 4) & 0x0F) | ((L << 4) & 0xF0);
	ClearFlags();
	ToggleFlag(Flag::Zero, L == 0);

	return 8;
}

/* SWAP (HL) */
unsigned int Processor::SWAP_MEM_HL() // 0x36
{
	uint8 val = memory->ReadByte(HL);
	memory->WriteByte(HL, ((val >> 4) & 0x0F) | ((val << 4) & 0xF0));
	ClearFlags();
	ToggleFlag(Flag::Zero, memory->ReadByte(HL) == 0);

	return 16;
}

/* SWAP A */
unsigned int Processor::SWAP_A() // 0x37
{
	A = ((A >> 4) & 0x0F) | ((A << 4) & 0xF0);
	ClearFlags();
	ToggleFlag(Flag::Zero, A == 0);

	return 8;
}

/* SRL B */
unsigned int Processor::SRL_B() // 0x38
{
	B = Srl(B);

	return 8;
}

/* SRL C */
unsigned int Processor::SRL_C() // 0x39
{
	C = Srl(C);

	return 8;
}

/* SRL D */
unsigned int Processor::SRL_D() // 0x3A
{
	D = Srl(D);

	return 8;
}

/* SRL E */
unsigned int Processor::SRL_E() // 0x3B
{
	E = Srl(E);

	return 8;
}

/* SRL H */
unsigned int Processor::SRL_H() // 0x3C
{
	H = Srl(H);

	return 8;
}

/* SRL L */
unsigned int Processor::SRL_L() // 0x3D
{
	L = Srl(L);

	return 8;
}

/* SRL (HL) */
unsigned int Processor::SRL_MEM_HL() // 0x3E
{
	memory->WriteByte(HL, Srl(memory->ReadByte(HL)));

	return 16;
}

/* SRL A */
unsigned int Processor::SRL_A() // 0x3F
{
	A = Srl(A);

	return 8;
}

/* BIT 0, B */
unsigned int Processor::BIT_0_B() // 0x40
{
	Bit(B, 0);

	return 8;
}

/* BIT 0, C */
unsigned int Processor::BIT_0_C() // 0x41
{
	Bit(C, 0);

	return 8;
}

/* BIT 0, D */
unsigned int Processor::BIT_0_D() // 0x42
{
	Bit(D, 0);

	return 8;
}

/* BIT 0, E */
unsigned int Processor::BIT_0_E() // 0x43
{
	Bit(E, 0);

	return 8;
}

/* BIT 0, H */
unsigned int Processor::BIT_0_H() // 0x44
{
	Bit(H, 0);

	return 8;
}

/* BIT 0, L */
unsigned int Processor::BIT_0_L() // 0x45
{
	Bit(L, 0);

	return 8;
}

/* BIT 0, (HL) */
unsigned int Processor::BIT_0_MEM_HL() // 0x46
{
	Bit(memory->ReadByte(HL), 0);

	return 12;
}

/* BIT 0, A */
unsigned int Processor::BIT_0_A() // 0x47
{
	Bit(A, 0);

	return 8;
}

/* BIT 1, B */
unsigned int Processor::BIT_1_B() // 0x48
{
	Bit(B, 1);

	return 8;
}

/* BIT 1, C */
unsigned int Processor::BIT_1_C() // 0x49
{
	Bit(C, 1);

	return 8;
}

/* BIT 1, D */
unsigned int Processor::BIT_1_D() // 0x4A
{
	Bit(D, 1);

	return 8;
}

/* BIT 1, E */
unsigned int Processor::BIT_1_E() // 0x4B
{
	Bit(E, 1);

	return 8;
}

/* BIT 1, H */
unsigned int Processor::BIT_1_H() // 0x4C
{
	Bit(H, 1);

	return 8;
}

/* BIT 1, L */
unsigned int Processor::BIT_1_L() // 0x4D
{
	Bit(L, 1);

	return 8;
}

/* BIT 1, (HL) */
unsigned int Processor::BIT_1_MEM_HL() // 0x4E
{
	Bit(memory->ReadByte(HL), 1);

	return 12;
}

/* BIT 1, A */
unsigned int Processor::BIT_1_A() // 0x4F
{
	Bit(A, 1);

	return 8;
}

/* BIT 2, B */
unsigned int Processor::BIT_2_B() // 0x50
{
	Bit(B, 2);

	return 8;
}

/* BIT 2, C */
unsigned int Processor::BIT_2_C() // 0x51
{
	Bit(C, 2);

	return 8;
}

/* BIT 2, D */
unsigned int Processor::BIT_2_D() // 0x52
{
	Bit(D, 2);

	return 8;
}

/* BIT 2, E */
unsigned int Processor::BIT_2_E() // 0x53
{
	Bit(E, 2);

	return 8;
}

/* BIT 2, H */
unsigned int Processor::BIT_2_H() // 0x54
{
	Bit(H, 2);

	return 8;
}

/* BIT 2, L */
unsigned int Processor::BIT_2_L() // 0x55
{
	Bit(L, 2);

	return 8;
}

/* BIT 2, (HL) */
unsigned int Processor::BIT_2_MEM_HL() // 0x56
{
	Bit(memory->ReadByte(HL), 2);

	return 12;
}

/* BIT 2, A */
unsigned int Processor::BIT_2_A() // 0x57
{
	Bit(A, 2);

	return 8;
}

/* BIT 3, B */
unsigned int Processor::BIT_3_B() // 0x58
{
	Bit(B, 3);

	return 8;
}

/* BIT 3, C */
unsigned int Processor::BIT_3_C() // 0x59
{
	Bit(C, 3);

	return 8;
}

/* BIT 3, D */
unsigned int Processor::BIT_3_D() // 0x5A
{
	Bit(D, 3);

	return 8;
}

/* BIT 3, E */
unsigned int Processor::BIT_3_E() // 0x5B
{
	Bit(E, 3);

	return 8;
}

/* BIT 3, H */
unsigned int Processor::BIT_3_H() // 0x5C
{
	Bit(H, 3);

	return 8;
}

/* BIT 3, L */
unsigned int Processor::BIT_3_L() // 0x5D
{
	Bit(L, 3);

	return 8;
}

/* BIT 3, (HL) */
unsigned int Processor::BIT_3_MEM_HL() // 0x5E
{
	Bit(memory->ReadByte(HL), 3);

	return 12;
}

/* BIT 3, A */
unsigned int Processor::BIT_3_A() // 0x5F
{
	Bit(A, 3);

	return 8;
}

/* BIT 4, B */
unsigned int Processor::BIT_4_B() // 0x60
{
	Bit(B, 4);

	return 8;
}

/* BIT 4, C */
unsigned int Processor::BIT_4_C() // 0x61
{
	Bit(C, 4);

	return 8;
}

/* BIT 4, D */
unsigned int Processor::BIT_4_D() // 0x62
{
	Bit(D, 4);

	return 8;
}

/* BIT 4, E */
unsigned int Processor::BIT_4_E() // 0x63
{
	Bit(E, 4);

	return 8;
}

/* BIT 4, H */
unsigned int Processor::BIT_4_H() // 0x64
{
	Bit(H, 4);

	return 8;
}

/* BIT 4, L */
unsigned int Processor::BIT_4_L() // 0x65
{
	Bit(L, 4);

	return 8;
}

/* BIT 4, (HL) */
unsigned int Processor::BIT_4_MEM_HL() // 0x66
{
	Bit(memory->ReadByte(HL), 4);

	return 12;
}

/* BIT 4, A */
unsigned int Processor::BIT_4_A() // 0x67
{
	Bit(A, 4);

	return 8;
}

/* BIT 5, B */
unsigned int Processor::BIT_5_B() // 0x68
{
	Bit(B, 5);

	return 8;
}

/* BIT 5, C */
unsigned int Processor::BIT_5_C() // 0x69
{
	Bit(C, 5);

	return 8;
}

/* BIT 5, D */
unsigned int Processor::BIT_5_D() // 0x6A
{
	Bit(D, 5);

	return 8;
}

/* BIT 5, E */
unsigned int Processor::BIT_5_E() // 0x6B
{
	Bit(E, 5);

	return 8;
}

/* BIT 5, H */
unsigned int Processor::BIT_5_H() // 0x6C
{
	Bit(H, 5);

	return 8;
}

/* BIT 5, L */
unsigned int Processor::BIT_5_L() // 0x6D
{
	Bit(L, 5);

	return 8;
}

/* BIT 5, (HL) */
unsigned int Processor::BIT_5_MEM_HL() // 0x6E
{
	Bit(memory->ReadByte(HL), 5);

	return 12;
}

/* BIT 5, A */
unsigned int Processor::BIT_5_A() // 0x6F
{
	Bit(A, 5);

	return 8;
}

/* BIT 6, B */
unsigned int Processor::BIT_6_B() // 0x70
{
	Bit(B, 6);

	return 8;
}

/* BIT 6, C */
unsigned int Processor::BIT_6_C() // 0x71
{
	Bit(C, 6);

	return 8;
}

/* BIT 6, D */
unsigned int Processor::BIT_6_D() // 0x72
{
	Bit(D, 6);

	return 8;
}

/* BIT 6, E */
unsigned int Processor::BIT_6_E() // 0x73
{
	Bit(E, 6);

	return 8;
}

/* BIT 6, H */
unsigned int Processor::BIT_6_H() // 0x74
{
	Bit(H, 6);

	return 8;
}

/* BIT 6, L */
unsigned int Processor::BIT_6_L() // 0x75
{
	Bit(L, 6);

	return 8;
}

/* BIT 6, (HL) */
unsigned int Processor::BIT_6_MEM_HL() // 0x76
{
	Bit(memory->ReadByte(HL), 6);

	return 12;
}

/* BIT 6, A */
unsigned int Processor::BIT_6_A() // 0x77
{
	Bit(A, 6);

	return 8;
}

/* BIT 7, B */
unsigned int Processor::BIT_7_B() // 0x78
{
	Bit(B, 7);

	return 8;
}

/* BIT 7, C */
unsigned int Processor::BIT_7_C() // 0x79
{
	Bit(C, 7);

	return 8;
}

/* BIT 7, D */
unsigned int Processor::BIT_7_D() // 0x7A
{
	Bit(D, 7);

	return 8;
}

/* BIT 7, E */
unsigned int Processor::BIT_7_E() // 0x7B
{
	Bit(E, 7);

	return 8;
}

/* BIT 7, H */
unsigned int Processor::BIT_7_H() // 0x7C
{
	Bit(H, 7);

	return 8;
}

/* BIT 7, L */
unsigned int Processor::BIT_7_L() // 0x7D
{
	Bit(L, 7);

	return 8;
}

/* BIT 7, (HL) */
unsigned int Processor::BIT_7_MEM_HL() // 0x7E
{
	Bit(memory->ReadByte(HL), 7);

	return 12;
}

/* BIT 7, A */
unsigned int Processor::BIT_7_A() // 0x7F
{
	Bit(A, 7);

	return 8;
}

/* RES 0, B */
unsigned int Processor::RES_0_B() // 0x80
{
	ResetBit(B, 0);

	return 8;
}

/* RES 0, C */
unsigned int Processor::RES_0_C() // 0x81
{
	ResetBit(C, 0);

	return 8;
}

/* RES 0, D */
unsigned int Processor::RES_0_D() // 0x82
{
	ResetBit(D, 0);

	return 8;
}

/* RES 0, E */
unsigned int Processor::RES_0_E() // 0x83
{
	ResetBit(E, 0);

	return 8;
}

/* RES 0, H */
unsigned int Processor::RES_0_H() // 0x84
{
	ResetBit(H, 0);

	return 8;
}

/* RES 0, L */
unsigned int Processor::RES_0_L() // 0x85
{
	ResetBit(L, 0);

	return 8;
}

/* RES 0, (HL) */
unsigned int Processor::RES_0_MEM_HL() // 0x86
{
	uint8 result = memory->ReadByte(HL);
	ResetBit(result, 0);
	memory->WriteByte(HL, result);

	return 16;
}

/* RES 0, A */
unsigned int Processor::RES_0_A() // 0x87
{
	ResetBit(A, 0);

	return 8;
}

/* RES 1, B */
unsigned int Processor::RES_1_B() // 0x88
{
	ResetBit(B, 1);

	return 8;
}

/* RES 1, C */
unsigned int Processor::RES_1_C() // 0x89
{
	ResetBit(C, 1);

	return 8;
}

/* RES 1, D */
unsigned int Processor::RES_1_D() // 0x8A
{
	ResetBit(D, 1);

	return 8;
}

/* RES 1, E */
unsigned int Processor::RES_1_E() // 0x8B
{
	ResetBit(E, 1);

	return 8;
}

/* RES 1, H */
unsigned int Processor::RES_1_H() // 0x8C
{
	ResetBit(H, 1);

	return 8;
}

/* RES 1, L */
unsigned int Processor::RES_1_L() // 0x8D
{
	ResetBit(L, 1);

	return 8;
}

/* RES 1, (HL) */
unsigned int Processor::RES_1_MEM_HL() // 0x8E
{
	uint8 result = memory->ReadByte(HL);
	ResetBit(result, 1);
	memory->WriteByte(HL, result);

	return 16;
}

/* RES 1, A */
unsigned int Processor::RES_1_A() // 0x8F
{
	ResetBit(A, 1);

	return 8;
}

/* RES 2, B */
unsigned int Processor::RES_2_B() // 0x90
{
	ResetBit(B, 2);

	return 8;
}

/* RES 2, C */
unsigned int Processor::RES_2_C() // 0x91
{
	ResetBit(C, 2);

	return 8;
}

/* RES 2, D */
unsigned int Processor::RES_2_D() // 0x92
{
	ResetBit(D, 2);

	return 8;
}

/* RES 2, E */
unsigned int Processor::RES_2_E() // 0x93
{
	ResetBit(E, 2);

	return 8;
}

/* RES 2, H */
unsigned int Processor::RES_2_H() // 0x94
{
	ResetBit(H, 2);

	return 8;
}

/* RES 2, L */
unsigned int Processor::RES_2_L() // 0x95
{
	ResetBit(L, 2);

	return 8;
}

/* RES 2, (HL) */
unsigned int Processor::RES_2_MEM_HL() // 0x96
{
	uint8 result = memory->ReadByte(HL);
	ResetBit(result, 2);
	memory->WriteByte(HL, result);

	return 16;
}

/* RES 2, A */
unsigned int Processor::RES_2_A() // 0x97
{
	ResetBit(A, 2);

	return 8;
}

/* RES 3, B */
unsigned int Processor::RES_3_B() // 0x98
{
	ResetBit(B, 3);

	return 8;
}

/* RES 3, C */
unsigned int Processor::RES_3_C() // 0x99
{
	ResetBit(C, 3);

	return 8;
}

/* RES 3, D */
unsigned int Processor::RES_3_D() // 0x9A
{
	ResetBit(D, 3);

	return 8;
}

/* RES 3, E */
unsigned int Processor::RES_3_E() // 0x9B
{
	ResetBit(E, 3);

	return 8;
}

/* RES 3, H */
unsigned int Processor::RES_3_H() // 0x9C
{
	ResetBit(H, 3);

	return 8;
}

/* RES 3, L */
unsigned int Processor::RES_3_L() // 0x9D
{
	ResetBit(L, 3);

	return 8;
}

/* RES 3, (HL) */
unsigned int Processor::RES_3_MEM_HL() // 0x9E
{
	uint8 result = memory->ReadByte(HL);
	ResetBit(result, 3);
	memory->WriteByte(HL, result);

	return 16;
}

/* RES 3, A */
unsigned int Processor::RES_3_A() // 0x9F
{
	ResetBit(A, 3);

	return 8;
}

/* RES 4, B */
unsigned int Processor::RES_4_B() // 0xA0
{
	ResetBit(B, 4);

	return 8;
}

/* RES 4, C */
unsigned int Processor::RES_4_C() // 0xA1
{
	ResetBit(C, 4);

	return 8;
}

/* RES 4, D */
unsigned int Processor::RES_4_D() // 0xA2
{
	ResetBit(D, 4);

	return 8;
}

/* RES 4, E */
unsigned int Processor::RES_4_E() // 0xA3
{
	ResetBit(E, 4);

	return 8;
}

/* RES 4, H */
unsigned int Processor::RES_4_H() // 0xA4
{
	ResetBit(H, 4);

	return 8;
}

/* RES 4, L */
unsigned int Processor::RES_4_L() // 0xA5
{
	ResetBit(L, 4);

	return 8;
}

/* RES 4, (HL) */
unsigned int Processor::RES_4_MEM_HL() // 0xA6
{
	uint8 result = memory->ReadByte(HL);
	ResetBit(result, 4);
	memory->WriteByte(HL, result);

	return 16;
}

/* RES 4, A */
unsigned int Processor::RES_4_A() // 0xA7
{
	ResetBit(A, 4);

	return 8;
}

/* RES 5, B */
unsigned int Processor::RES_5_B() // 0xA8
{
	ResetBit(B, 5);

	return 8;
}

/* RES 5, C */
unsigned int Processor::RES_5_C() // 0xA9
{
	ResetBit(C, 5);

	return 8;
}

/* RES 5, D */
unsigned int Processor::RES_5_D() // 0xAA
{
	ResetBit(D, 5);

	return 8;
}

/* RES 5, E */
unsigned int Processor::RES_5_E() // 0xAB
{
	ResetBit(E, 5);

	return 8;
}

/* RES 5, H */
unsigned int Processor::RES_5_H() // 0xAC
{
	ResetBit(H, 5);

	return 8;
}

/* RES 5, L */
unsigned int Processor::RES_5_L() // 0xAD
{
	ResetBit(L, 5);

	return 8;
}

/* RES 5, (HL) */
unsigned int Processor::RES_5_MEM_HL() // 0xAE
{
	uint8 result = memory->ReadByte(HL);
	ResetBit(result, 5);
	memory->WriteByte(HL, result);

	return 16;
}

/* RES 5, A */
unsigned int Processor::RES_5_A() // 0xAF
{
	ResetBit(A, 5);

	return 8;
}

/* RES 6, B */
unsigned int Processor::RES_6_B() // 0xB0
{
	ResetBit(B, 6);

	return 8;
}

/* RES 6, C */
unsigned int Processor::RES_6_C() // 0xB1
{
	ResetBit(C, 6);

	return 8;
}

/* RES 6, D */
unsigned int Processor::RES_6_D() // 0xB2
{
	ResetBit(D, 6);

	return 8;
}

/* RES 6, E */
unsigned int Processor::RES_6_E() // 0xB3
{
	ResetBit(E, 6);

	return 8;
}

/* RES 6, H */
unsigned int Processor::RES_6_H() // 0xB4
{
	ResetBit(H, 6);

	return 8;
}

/* RES 6, L */
unsigned int Processor::RES_6_L() // 0xB5
{
	ResetBit(L, 6);

	return 8;
}

/* RES 6, (HL) */
unsigned int Processor::RES_6_MEM_HL() // 0xB6
{
	uint8 result = memory->ReadByte(HL);
	ResetBit(result, 6);
	memory->WriteByte(HL, result);

	return 16;
}

/* RES 6, A */
unsigned int Processor::RES_6_A() // 0xB7
{
	ResetBit(A, 6);

	return 8;
}

/* RES 7, B */
unsigned int Processor::RES_7_B() // 0xB8
{
	ResetBit(B, 7);

	return 8;
}

/* RES 7, C */
unsigned int Processor::RES_7_C() // 0xB9
{
	ResetBit(C, 7);

	return 8;
}

/* RES 7, D */
unsigned int Processor::RES_7_D() // 0xBA
{
	ResetBit(D, 7);

	return 8;
}

/* RES 7, E */
unsigned int Processor::RES_7_E() // 0xBB
{
	ResetBit(E, 7);

	return 8;
}

/* RES 7, H */
unsigned int Processor::RES_7_H() // 0xBC
{
	ResetBit(H, 7);

	return 8;
}

/* RES 7, L */
unsigned int Processor::RES_7_L() // 0xBD
{
	ResetBit(L, 7);

	return 8;
}

/* RES 7, (HL) */
unsigned int Processor::RES_7_MEM_HL() // 0xBE
{
	uint8 result = memory->ReadByte(HL);
	ResetBit(result, 7);
	memory->WriteByte(HL, result);

	return 16;
}

/* RES 7, A */
unsigned int Processor::RES_7_A() // 0xBF
{
	ResetBit(A, 7);

	return 8;
}

/* SET 0, B */
unsigned int Processor::SET_0_B() // 0xC0
{
	SetBit(B, 0);

	return 8;
}

/* SET 0, C */
unsigned int Processor::SET_0_C() // 0xC1
{
	SetBit(C, 0);

	return 8;
}

/* SET 0, D */
unsigned int Processor::SET_0_D() // 0xC2
{
	SetBit(D, 0);

	return 8;
}

/* SET 0, E */
unsigned int Processor::SET_0_E() // 0xC3
{
	SetBit(E, 0);

	return 8;
}

/* SET 0, H */
unsigned int Processor::SET_0_H() // 0xC4
{
	SetBit(H, 0);

	return 8;
}

/* SET 0, L */
unsigned int Processor::SET_0_L() // 0xC5
{
	SetBit(L, 0);

	return 8;
}

/* SET 0, (HL) */
unsigned int Processor::SET_0_MEM_HL() // 0xC6
{
	uint8 result = memory->ReadByte(HL);
	SetBit(result, 0);
	memory->WriteByte(HL, result);

	return 16;
}

/* SET 0, A */
unsigned int Processor::SET_0_A() // 0xC7
{
	SetBit(A, 0);

	return 8;
}

/* SET 1, B */
unsigned int Processor::SET_1_B() // 0xC8
{
	SetBit(B, 1);

	return 8;
}

/* SET 1, C */
unsigned int Processor::SET_1_C() // 0xC9
{
	SetBit(C, 1);

	return 8;
}

/* SET 1, D */
unsigned int Processor::SET_1_D() // 0xCA
{
	SetBit(D, 1);

	return 8;
}

/* SET 1, E */
unsigned int Processor::SET_1_E() // 0xCB
{
	SetBit(E, 1);

	return 8;
}

/* SET 1, H */
unsigned int Processor::SET_1_H() // 0xCC
{
	SetBit(H, 1);

	return 8;
}

/* SET 1, L */
unsigned int Processor::SET_1_L() // 0xCD
{
	SetBit(L, 1);

	return 8;
}

/* SET 1, (HL) */
unsigned int Processor::SET_1_MEM_HL() // 0xCE
{
	uint8 result = memory->ReadByte(HL);
	SetBit(result, 1);
	memory->WriteByte(HL, result);

	return 16;
}

/* SET 1, A */
unsigned int Processor::SET_1_A() // 0xCF
{
	SetBit(A, 1);

	return 8;
}

/* SET 2, B */
unsigned int Processor::SET_2_B() // 0xD0
{
	SetBit(B, 2);

	return 8;
}

/* SET 2, C */
unsigned int Processor::SET_2_C() // 0xD1
{
	SetBit(C, 2);

	return 8;
}

/* SET 2, D */
unsigned int Processor::SET_2_D() // 0xD2
{
	SetBit(D, 2);

	return 8;
}

/* SET 2, E */
unsigned int Processor::SET_2_E() // 0xD3
{
	SetBit(E, 2);

	return 8;
}

/* SET 2, H */
unsigned int Processor::SET_2_H() // 0xD4
{
	SetBit(H, 2);

	return 8;
}

/* SET 2, L */
unsigned int Processor::SET_2_L() // 0xD5
{
	SetBit(L, 2);

	return 8;
}

/* SET 2, (HL) */
unsigned int Processor::SET_2_MEM_HL() // 0xD6
{
	uint8 result = memory->ReadByte(HL);
	SetBit(result, 2);
	memory->WriteByte(HL, result);

	return 16;
}

/* SET 2, A */
unsigned int Processor::SET_2_A() // 0xD7
{
	SetBit(A, 2);

	return 8;
}

/* SET 3, B */
unsigned int Processor::SET_3_B() // 0xD8
{
	SetBit(B, 3);

	return 8;
}

/* SET 3, C */
unsigned int Processor::SET_3_C() // 0xD9
{
	SetBit(C, 3);

	return 8;
}

/* SET 3, D */
unsigned int Processor::SET_3_D() // 0xDA
{
	SetBit(D, 3);

	return 8;
}

/* SET 3, E */
unsigned int Processor::SET_3_E() // 0xDB
{
	SetBit(E, 3);

	return 8;
}

/* SET 3, H */
unsigned int Processor::SET_3_H() // 0xDC
{
	SetBit(H, 3);

	return 8;
}

/* SET 3, L */
unsigned int Processor::SET_3_L() // 0xDD
{
	SetBit(L, 3);

	return 8;
}

/* SET 3, (HL) */
unsigned int Processor::SET_3_MEM_HL() // 0xDE
{
	uint8 result = memory->ReadByte(HL);
	SetBit(result, 3);
	memory->WriteByte(HL, result);

	return 16;
}

/* SET 3, A */
unsigned int Processor::SET_3_A() // 0xDF
{
	SetBit(A, 3);

	return 8;
}

/* SET 4, B */
unsigned int Processor::SET_4_B() // 0xE0
{
	SetBit(B, 4);

	return 8;
}

/* SET 4, C */
unsigned int Processor::SET_4_C() // 0xE1
{
	SetBit(C, 4);

	return 8;
}

/* SET 4, D */
unsigned int Processor::SET_4_D() // 0xE2
{
	SetBit(D, 4);

	return 8;
}

/* SET 4, E */
unsigned int Processor::SET_4_E() // 0xE3
{
	SetBit(E, 4);

	return 8;
}

/* SET 4, H */
unsigned int Processor::SET_4_H() // 0xE4
{
	SetBit(H, 4);

	return 8;
}

/* SET 4, L */
unsigned int Processor::SET_4_L() // 0xE5
{
	SetBit(L, 4);

	return 8;
}

/* SET 4, (HL) */
unsigned int Processor::SET_4_MEM_HL() // 0xE6
{
	uint8 result = memory->ReadByte(HL);
	SetBit(result, 4);
	memory->WriteByte(HL, result);

	return 16;
}

/* SET 4, A */
unsigned int Processor::SET_4_A() // 0xE7
{
	SetBit(A, 4);

	return 8;
}

/* SET 5, B */
unsigned int Processor::SET_5_B() // 0xE8
{
	SetBit(B, 5);

	return 8;
}

/* SET 5, C */
unsigned int Processor::SET_5_C() // 0xE9
{
	SetBit(C, 5);

	return 8;
}

/* SET 5, D */
unsigned int Processor::SET_5_D() // 0xEA
{
	SetBit(D, 5);

	return 8;
}

/* SET 5, E */
unsigned int Processor::SET_5_E() // 0xEB
{
	SetBit(E, 5);

	return 8;
}

/* SET 5, H */
unsigned int Processor::SET_5_H() // 0xEC
{
	SetBit(H, 5);

	return 8;
}

/* SET 5, L */
unsigned int Processor::SET_5_L() // 0xED
{
	SetBit(L, 5);

	return 8;
}

/* SET 5, (HL) */
unsigned int Processor::SET_5_MEM_HL() // 0xEE
{
	uint8 result = memory->ReadByte(HL);
	SetBit(result, 5);
	memory->WriteByte(HL, result);

	return 16;
}

/* SET 5, A */
unsigned int Processor::SET_5_A() // 0xEF
{
	SetBit(A, 5);

	return 8;
}

/* SET 6, B */
unsigned int Processor::SET_6_B() // 0xF0
{
	SetBit(B, 6);

	return 8;
}

/* SET 6, C */
unsigned int Processor::SET_6_C() // 0xF1
{
	SetBit(C, 6);

	return 8;
}

/* SET 6, D */
unsigned int Processor::SET_6_D() // 0xF2
{
	SetBit(D, 6);

	return 8;
}

/* SET 6, E */
unsigned int Processor::SET_6_E() // 0xF3
{
	SetBit(E, 6);

	return 8;
}

/* SET 6, H */
unsigned int Processor::SET_6_H() // 0xF4
{
	SetBit(H, 6);

	return 8;
}

/* SET 6, L */
unsigned int Processor::SET_6_L() // 0xF5
{
	SetBit(L, 6);

	return 8;
}

/* SET 6, (HL) */
unsigned int Processor::SET_6_MEM_HL() // 0xF6
{
	uint8 result = memory->ReadByte(HL);
	SetBit(result, 6);
	memory->WriteByte(HL, result);

	return 16;
}

/* SET 6, A */
unsigned int Processor::SET_6_A() // 0xF7
{
	SetBit(A, 6);

	return 8;
}

/* SET 7, B */
unsigned int Processor::SET_7_B() // 0xF8
{
	SetBit(B, 7);

	return 8;
}

/* SET 7, C */
unsigned int Processor::SET_7_C() // 0xF9
{
	SetBit(C, 7);

	return 8;
}

/* SET 7, D */
unsigned int Processor::SET_7_D() // 0xFA
{
	SetBit(D, 7);

	return 8;
}

/* SET 7, E */
unsigned int Processor::SET_7_E() // 0xFB
{
	SetBit(E, 7);

	return 8;
}

/* SET 7, H */
unsigned int Processor::SET_7_H() // 0xFC
{
	SetBit(H, 7);

	return 8;
}

/* SET 7, L */
unsigned int Processor::SET_7_L() // 0xFD
{
	SetBit(L, 7);

	return 8;
}

/* SET 7, (HL) */
unsigned int Processor::SET_7_MEM_HL() // 0xFE
{
	uint8 result = memory->ReadByte(HL);
	SetBit(result, 7);
	memory->WriteByte(HL, result);

	return 16;
}

/* SET 7, A */
unsigned int Processor::SET_7_A() // 0xFF
{
	SetBit(A, 7);

	return 8;
}

